### ISSUE TITLE
fastcgi_params file set to permission 770 by default

### ISSUE THREAD

**Issue by jarro2783** [voxpupuli/puppet-nginx#1002]
For all versions of the Puppet module, the `fastcgi_params` file is set to permissions 770. This seems really weird to me. Since it is a normal file, it should be 644 like everything else.

**Comment by wyardley** [comment]
I'm not sure why that is, but I'm going to propose a PR to change `fastcgi_params` and `uwsgi_params`. I'll solicit some input before getting it approved to make sure there's not a reason for those permissions. I don't know why they're not world readable either, I don't think there should be anything sensitive in those files (maybe it's matching the permissions in some vendor-distributed version of the file?)

What's odd to me is that the permissions actually aren't 0770 on a system where I'm using this module...

**Comment by jarro2783** [comment]
Actually I noticed the same thing on one of our hosts. On a different host it is always 0770. Not sure why it is doing that.

**Comment by wyardley** [comment]
@jarro2783 Are you setup in such a way that you can test this PR? That said, if no one else sees a reason for the original permissions, I think this one is ready to merge.

**Comment by jarro2783** [comment]
I can only test it against 0.5.0. I don't know how Puppet module spec tests are run, but I can at least verify that the output file has the right permissions on one of our hosts.
