### ISSUE TITLE
How to add conf files to /etc/nginx/conf.d

### ISSUE THREAD

**Issue by hellraiser2005** [voxpupuli/puppet-nginx#1017]
I cannot find any documentation to add new conf files to /etc/nginx/conf.d

**Comment by ubellavance** [comment]
I don't think there is a way to do so. The conf.d folder is a directory where the files for server (vhost) configs are created. What are you trying to achieve?

**Comment by hellraiser2005** [comment]
I was trying to add an blacklist.conf so that i can block bots, hitting my site.

**Comment by ubellavance** [comment]
In what section would you normally add the directives? http?  http_cfg_append could be useful for you.  If not, search for "append" or "prepend" in this repo. You'll find options to add custom code to your config.  I think it's available in all section (nginx, http, server, location).

**Comment by wyardley** [comment]
Short answer, there are a couple ways to accomplish this.

If it's something you want to embed in a specific server block, I agree with @ubellavance about looking at the various custom / raw apend / prepend options available.

If you're not using `confd_purge` param (or `confd_purge` + `confd_only`),  you can push files to that directory from a site manifest or profile directly, and they shouldn't get purged. `confd_purge` defaults to false. The default use case of the module is to put the sites into `/etc/nginx/sites-available` and leave `conf.d` alone.

Or, you could create another include directory in the main nginx.conf (using one of the raw config directives) and then drop the file in there.

**Comment by wyardley** [comment]
Hope this helped; re-open if you need more assistance.
