### ISSUE TITLE
Can't pass 'always' parameter to add_header due to single quoting

### ISSUE THREAD

**Issue by benh57** [voxpupuli/puppet-nginx#1020]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.9.2
- Distribution: Centos 7
- Module version: 0.6.1

## How to reproduce (e.g Puppet code you use)

    nginx::resource::server { 'foo':
      add_header           => { 'Access-Control-Allow-Origin'      => '"*" always' } ,
}

## What are you seeing

Results in config:

  add_header              'Access-Control-Allow-Origin' '"*" always';

Which breaks in Chrome:
The 'Access-Control-Allow-Origin' header contains multiple values '"*" always', but only one is allowed.

## What behaviour did you expect instead

This formerly generated:

  add_header              'Access-Control-Allow-Origin'  "*" always;

## Any additional information you'd like to impart

Related to https://github.com/voxpupuli/puppet-nginx/issues/991

**Comment by wyardley** [comment]
If you're able, can you test https://github.com/voxpupuli/puppet-nginx/pull/992 ?

**Comment by benh57** [comment]
Indeed, this does appear to work! I expected it would not. I just have to modify my puppet-side code to not use the double quotes:
  add_header           => { 'Access-Control-Allow-Origin'      => '* always' } ,

Then i get this in the config:

  add_header              'Access-Control-Allow-Origin' "* always";

And Chrome appears to get the star, properly, and not the 'always'.

So it's still a breaking change from my previous config where i had my own double quotes around the star.

thanks!

**Comment by benh57** [comment]
I suppose this parameter should be validated with a regex to ensure that the user isn't passing a nonescaped quote/ double quote. Since that breaks nginx when it's quoted again.

**Comment by wyardley** [comment]
@benh57 Yeah, though see the comments from @xaque208 in that issue, my reading is that maybe double quotes aren't legal in header values anyway? I'm a bit worried that adding such validation might almost be a cure that's worse than the disease?

I'm hoping someone will merge that issue soon, since it seems like at least an improvement over the current situation.
