### ISSUE TITLE
README regarding Hiera is not up to date anymore

### ISSUE THREAD

**Issue by ryayon** [voxpupuli/puppet-nginx#1024]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: ALL
- Ruby: ALL
- Distribution: ALL
- Module version: N/A

**Comment by ryayon** [comment]
I just created PR #1025

**Comment by rnelson0** [comment]
As described in the PR, the hiera settings are correct. If there is something more specific about the hiera docs that need changed, please describe it in detail in a new ticket, thanks!
