### ISSUE TITLE
Support for ngx_http_autoindex_module

### ISSUE THREAD

**Issue by shendrickx** [voxpupuli/puppet-nginx#1027]
The current version of the module supports the autoindex option. However, several other options from ngx_http_autoindex_module are not supported like: autoindex_localtime, autoindex_exact_size and autoindex_format. Would it be possible to add support for these parameters as well?

**Comment by Rubueno** [comment]
While my pull request is pending, I have found that you can use `location_raw_append`, add an array with your `autoindex` values, much like the following:

```
location_raw_append => ['autoindex_exact_size off;', 'autoindex_localtime on;'],
```
