### ISSUE TITLE
Make ssl_prefer_server_ciphers a variable

### ISSUE THREAD

**Issue by fbjerggaard** [voxpupuli/puppet-nginx#1032]
ssl_prefer_server_ciphers should be possible to set via a variable when defining a vhost and not be hardcoded to `on`

**Comment by wyardley** [comment]
@fbjerggaard I haven't been contributing much recently, but this seems pretty simple, can you see if #1067 works for your use case? I will seek out some feedback on it as well.

**Comment by fbjerggaard** [comment]
Looks fine to me
Let's see if the owners of the module agree

**Comment by wyardley** [comment]
@fbjerggaard Approved / merged.  I've reworked it slightly, but the outcome should be the same.
