### ISSUE TITLE
Custom nginx.conf template is no longer working

### ISSUE THREAD

**Issue by auth00** [voxpupuli/puppet-nginx#1083]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.7
- Ruby: 1.9.3p484
- Distribution: Ubuntu 14.04
- Module version: v0.6.0

## How to reproduce (e.g Puppet code you use)
Have some special nginx config that makes you want to override the nginx.conf template. In my example I want to remove server_names_hash_bucket_size from nginx.conf.

## What are you seeing
In #272 code to allow a custom nginx.conf template by configuration was introduced. This parameter is now hard coded instead.

## What behaviour did you expect instead
To be able to continue using a custom nginx.conf template.

## Output log
--

## Any additional information you'd like to impart
--

**Comment by jsmelser** [comment]
yeah, this breaks for me. I need an include in my nginx config and this does not provide a way to add an include line or to overwrite the conf file.

**Comment by wyardley** [comment]
@jsmelser I don't believe there's a way not to manage the config, but there is a way to add additional arbitrary variables. see `http_cfg_prepend`, `http_cfg_append`, `nginx_cfg_prepend` and so on. Additionally, you can drop down additional files from your site-specific code into e.g., `conf_dir/conf.d/foo.conf`, which, under the default settings, will not get cleaned up / purged.

It would be trivial to make certain options, such as `server_names_hash_bucket_size`, optional, and that's the path that the module is taking for the most part.

@auth00: I think you could also override the file resource from the module if you really needed to, see 
http://stackoverflow.com/questions/30016279/puppet-overriding-file-resource-on-a-module

If you can let us know all the parameters you need to suppress, we can see if someone can submit a PR to make those parameters optional for ones that aren't already.

**Comment by jsmelser** [comment]
I am sorry, I did not see the above response.  I was able to add my changes in a different way but still through the module. This isnt as breaking as I thought. My apologies on that.
