### ISSUE TITLE
ssl_dhparam no longer an option

### ISSUE THREAD

**Issue by sk33lz** [voxpupuli/puppet-nginx#1084]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.0
- Ruby: ruby 2.0.0p648
- Distribution: Ubuntu 16.04
- Module version: 0.6.0

## How to reproduce (e.g Puppet code you use)

Add `ssl_dhparam => '/path/to/dh.params.file',` to a manifest file that has SSL enabled.

## What are you seeing

You can no longer use the `ssl_dhparam` option in a manifest file in the puppet/nginx module, as it's not defined in the module.

## What behaviour did you expect instead

In the [jfryman/nginx 0.3.0](https://forge.puppet.com/jfryman/nginx/0.3.0/readme) version of this module you could setup an ssl_dhparam option for SSL that adds Diffie–Hellman key exchange for SSL.

**Comment by wyardley** [comment]
Can you show the exact declaration you're using? It appears to be supported, e.g., https://github.com/voxpupuli/puppet-nginx/blob/master/manifests/resource/server.pp#L44

https://github.com/voxpupuli/puppet-nginx/blob/master/templates/server/server_ssl_settings.erb#L13-L15

the mailhost resource has similar settings.

**Comment by sk33lz** [comment]
You are right. It helps if I generate the pem file locally first :|
