### ISSUE TITLE
Bump puppetlabs/apt dependency

### ISSUE THREAD

**Issue by den-is** [voxpupuli/puppet-nginx#1086]
```
Warning: Module 'puppetlabs-apt' (v4.0.0) fails to meet some dependencies:
  'puppet-nginx' (v0.6.0) requires 'puppetlabs-apt' (>= 2.1.0 <3.0.0)
```
According to the Puppet Style Guide https://docs.puppet.com/puppet/latest/style_guide.html#dependencies , epel and apt are soft dependencies and should be treated as such.

**Comment by cfoehrdes** [comment]
We are also experiencing a lot of conflicts due to puppet-nginx referencing hard to this old apt module

**Comment by wyardley** [comment]
How about #1106 as a fix for this?

**Comment by cristianbalan** [comment]
Any development here please?

**Comment by cristianbalan** [comment]
Sorry, what's the conclusion to this? I face the same problem.
> Warning: Module 'puppetlabs-apt' (v3.0.0) fails to meet some dependencies:
>   'puppet-nginx' (v0.6.0) requires 'puppetlabs-apt' (>= 2.1.0 <3.0.0)
Upgrading the module to 0.7.0 would still be requiring the old module but would not throw the warning?

**Comment by wyardley** [comment]
@cristianbalan take a look at the changes in:
https://github.com/voxpupuli/puppet-nginx/pull/1106/files
now that it's a soft dependency, the module is not explicitly required; you're just responsible for making sure that an appropriate version of the apt module is available.

**Comment by cristianbalan** [comment]
Looks perfect @wyardley! Any plan to push that to Forge at some point in the next days?
Thanks.
