### ISSUE TITLE
Add support for the `underscores_in_headers` option

### ISSUE THREAD

**Issue by tedivm** [voxpupuli/puppet-nginx#1089]
There's currently no way to enable `underscores_in_headers` using this puppet module.

**Comment by wyardley** [comment]
PRs (with tests) to add this directive explicitly would be happily accepted; that said, there is currently a way to add this in both valid contexts.

To add to main nginx config:
```
    class { 'nginx':
      http_cfg_append => { 'underscores_in_headers' => 'on' },
    }
```
or to put in server block
```
      nginx::resource::server { 'www.puppetlabs.com':
        www_root => '/var/www/www.puppetlabs.com',
        server_cfg_prepend => { 'underscores_in_headers' => 'on', }
      }
```
(use prepend / apend depending on where you want it). You can use the same idea if you're
using Hiera to configure, e.g. something like (untested)
```
nginx:
  http_cfg_append:
    underscores_in_headers: 'on'
```
