### ISSUE TITLE
puppet-nginx requires outdated module dependencies

### ISSUE THREAD

**Issue by fnoop** [voxpupuli/puppet-nginx#1107]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.0.0
- Ruby: 2.1.3
- Distribution: Ubuntu 16.04
- Module version: 0.7, 0.71rc

## How to reproduce (e.g Puppet code you use)
puppet module install puppet-nginx

## What are you seeing
Module fails to install with missing dependencies.  If I force install, I see:
```
Warning: Module 'puppetlabs-apt' (v4.1.0) fails to meet some dependencies:
  'puppet-nginx' (v0.7.1-rc0) requires 'puppetlabs-apt' (>= 2.1.0 <3.0.0)
Warning: Module 'puppetlabs-concat' (v4.0.0) fails to meet some dependencies:
  'puppet-nginx' (v0.7.1-rc0) requires 'puppetlabs-concat' (>= 3.0.0 <4.0.0)
```
The modules I have installed are:
puppetlabs-concat (v4.0.0)
puppetlabs-apt (v4.1.0)

## What behaviour did you expect instead
To install cleanly.

**Comment by wyardley** [comment]
@fnoop check out #1106 - the style guide wants apt to be a soft dependency anyway.

I created #1108 which just sets concat to <  5.0.0 instead of <4.0.0; I think the module does work with 4.x, and it was probably specified that way to avoid an error from not having an upper limit on the require?

**Comment by fnoop** [comment]
@wyardley @alexjfisher Works great, thanks :)
