### ISSUE TITLE
Unable to include module's

### ISSUE THREAD

**Issue by iyappan-dcis** [voxpupuli/puppet-nginx#1112]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5
- Ruby:
- Distribution: Centos 7
- Module version: v0.7.0

## What are you seeing
How do I include module nginx-module-geoip in nginx configuration

## What behaviour did you expect instead
I want the below line to be included in nginx.conf 
load_module modules/ngx_http_geoip_module.so;

**Comment by danielpo** [comment]
Hi,
You can find a solution here:
https://github.com/voxpupuli/puppet-nginx/issues/766

**Comment by iyappan-dcis** [comment]
@danielpo Thanks alot. 

Also is there a way to include custom log format in nginx.conf ?

**Comment by wyardley** [comment]
@iyappan-dcis yes, custom logs can be setup in various scopes, though it's not 100% consistent in terms of how you do it. 

Docs could be better, but basically it's a hash with the format name as the key and the format as the value. There's an example in
https://github.com/voxpupuli/puppet-nginx/issues/678

**Comment by iyappan-dcis** [comment]
@wyardley Thanks for your time. I will check this.
