### ISSUE TITLE
Unable to 'set' a variable using the module

### ISSUE THREAD

**Issue by cptcanuck** [voxpupuli/puppet-nginx#1113]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4
- Ruby:
- Distribution: CentOS
- Module version: 0.5.0 (checked 0.7.0 as well)

## How to reproduce (e.g Puppet code you use)
N/A

## What are you seeing
N/A

## What behaviour did you expect instead
I am trying to setup my vhost/server to work as described here: https://serverfault.com/questions/240476/how-to-force-nginx-to-resolve-dns-of-a-dynamic-hostname-everytime-when-doing-p

so that I can trigger re-resolution when the TTL expires.  The appraoch seems to be to set a variable using the 'set' directive, but I cannot find any way to actually use the 'set' directive

**Comment by cptcanuck** [comment]
I can probably hack something up to contribute, but it likely won't be 'right' as I'm not much of a magician.  I assume you can have multiple 'sets' in a configuration block, so it would look something like this (Hiera style):

`nginx::nginx_vhosts:
  'api.site.com':
    proxy: '$site'
    resolver:
      - 172.31.0.2
    set:
      - "$site": "http://api.internal.site.com"
`
And then a template block like:

`<% if Array(@set).count > 0 -%>
  set                  <% Array(@set).each do |k,v| %> <%= k %><%= v %><% end %>;
<% end -%>
`

Maybe?  I'm pretty bad at this stuff!

**Comment by wyardley** [comment]
You can do something with `raw_append` or `raw_prepend`, e.g.,
```
  raw_append => ['set $site" "http://example.com";'],
```
(note, your syntax above can be accommodated this way too, though it doesn't seem to be valid on the version of Nginx I have).

Or, use `server_cfg_append` / `server_cfg_prepend` (there are similar bits for location blocks):
```
  server_cfg_prepend => {'set' => '"$site" "http://example.com"' }
```
[generates]
```
  set "$site" "http://example.com";
```

The latter is more structured, the former will accommodate multiple lines or more complex formatting, like in your example above.

**Comment by wyardley** [comment]
[these will work via `nginx::nginx_servers` as well]

**Comment by cptcanuck** [comment]
Excellent!  Thank you all very much for the guidance.  I hadn't come across the more generic append/prepend options.  My mistake!

**Comment by cptcanuck** [comment]
I ended up with this in hiera, for anyone who finds this in the future, and because I couldn't find a good example of the correct syntax:


`nginx::nginx_vhosts:
  'api.site.com':
    proxy: '$api_host'
    resolver:
      - 127.0.01
    location_cfg_append:
      set: '"$api_host" http://apihost.internal.site.com'
`

tested it and I'm seeing a DNS query per hit (which might concern me in the future, but it'll be cached so we should be fine).
