### ISSUE TITLE
Support puppetlabs/concat >= 4.0

### ISSUE THREAD

**Issue by khaefeli** [voxpupuli/puppet-nginx#1117]
this module has the following dependencies:

> puppetlabs/concat (>= 3.0.0 <4.0.0)
> puppetlabs/apt (>= 2.1.0 <3.0.0)

which is blocking me, from upgrading and using the latest `puppetlabs/concat` and `puppetlabs/apt` version.
is it planned to support it in future?

**Comment by wyardley** [comment]
Handled already in #1108, however, has not been released yet. Current git master should work.

I'll see if it's feasible to get a release cut soon.

**Comment by wyardley** [comment]
Submitted #1118 for the bump, will release once that's reviewed / merged.
