### ISSUE TITLE
Feature request: rate limiting (limit_req_zone, limit_req)

### ISSUE THREAD

**Issue by khaefeli** [voxpupuli/puppet-nginx#1134]
(D)DoS, brute force attacks etc are everywhere.
We want to protect our backends from excessive requests and load.
Nginx is supporting rate limiting in the `ngx_http_limit_req_module` module:
https://www.nginx.com/blog/rate-limiting-nginx/

Bring this feature as default to the puppet nginx core and help people to protect their backends.

**Comment by wyardley** [comment]
I agree that we'll need a better way of handling modules at some point. I'm not sure that this should be the default configuration, though.
For now, installing the module itself may need to be handled outside of the module, though configuring its directives should be possible with the existing tooling.

**Comment by khaefeli** [comment]
sorry, I was a little bit inaccurate in my description:
support it with the puppet nginx module, but don't enable it by default. 

Actually, it's not a 3rd party module. 
It's nginx core - so you just need to enable  ̀limit_req_zone` in the http section and map the  ̀limit_req zone=mylimit` in the location section. I could create a PR if you want.

**Comment by khaefeli** [comment]
no, that's `limit_conn' - I'm talking about `limit_req` :)

**Comment by ubellavance** [comment]
Ok can you achieve it using a `location_custom_cfg_append`? But in any case, my definition of a puppet module is that it should allow the user do do a lot of stuff (ideally everything that the target service allows), but not change the default settings.

**Comment by khaefeli** [comment]
sure. you could link the zone to the location with `location_custom_cfg_append` (including options) and add the zones via `server_cfg_append`. I could also create some config files and include them. But that's more a bad workaround from my point of view.
currently there are ~120 server and ~110 location parameters. Why not supporting this important core option? :)

**Comment by ubellavance** [comment]
Hi @khaefeli,

I have nothing against the fact that this core feature should be supported. You even offered to create a PR, which is very positive.  My only opinion is that limit_req should not be enabled by default by the module.  But again, this is very good news, thanks!

**Comment by absltkaos** [comment]
I submitted a PR, it doesn't enable request limiting by default, but it does expose it for configuring now.
