### ISSUE TITLE
Feature request: assign nginx location to multiple servers

### ISSUE THREAD

**Issue by hostingnuggets** [voxpupuli/puppet-nginx#1135]
Right now an nginx location config can only be assigned to one single nginx server passing it as a String. It would be nice to be able to define one nginx location and re-use it for multiple nginx servers. This could be done by passing an Array instead of a String. Here is an example of what I mean using hiera YAML config:  

```
nginx::nginx_locations:
  'acme-challenge':
    location: '/.well-known/acme-challenge'
    server: ['www.domain1.com', 'www.domain2.com']
```

This would avoid having to duplicate nginx location config blocks for multiple websites and hence have a shorter and cleaner config following DRY.

**Comment by kwisatz** [comment]
Just look this up, because in a recent set-up, I would have benefited a great deal from this.

**Comment by tinuzz** [comment]
For this use case, I use

'include_files'  => [ 'snippets/letsencrypt-acme-challenge.conf' ],

in all servers.

**Comment by dndprude** [comment]
Moving to this module from jfryman-nginx and this functionality was used heavily in our setup. Let's encrypt is far from the only usage case in which multiple vhosts will require the same location definitions.

**Comment by ekohl** [comment]
@dndprude this module was migrated (and renamed) from jfryman-nginx so I'm surprised if the functionality was actually removed.
