### ISSUE TITLE
http_format_log for nginx servers 

### ISSUE THREAD

**Issue by hostingnuggets** [voxpupuli/puppet-nginx#1139]
The `nginx::http_format_log` config parameter only applies to the main nginx.conf file. It would be nice to have the possibility to customize the log format per nginx server. For example by using the following hiera config parameter:
```
nginx::nginx_servers:
  'www.mywebsite.com':
    http_format_log: 'special'
...
 ```

**Comment by wyardley** [comment]
The  `log_format` directive is only valid in http context:
http://nginx.org/en/docs/http/ngx_http_log_module.html#log_format
That said, you can create as many log_formats as you want, and reference them from a specific server block.

**Comment by hostingnuggets** [comment]
I might have not been quite clear: what I would like to do is from my nginx server blocks to use a specific log_format which of course I would have defined in the http context as you correctly mention. This is currently not possible as the `access_log` parameter in the server block does not allow you to pass a custom log_format, it always and automatically defaults to `combined`. Or did I miss something?

**Comment by alexjfisher** [comment]
I'm pretty sure this is already possible.  I use this module with json formatted logs.
As well as the `access_log` parameter, there is also [`format_log`](https://github.com/voxpupuli/puppet-nginx/blob/a1718db2350403a8dcf73aff67cfeb23192ae6db/manifests/resource/server.pp#L234).

**Comment by alexjfisher** [comment]
Ah right, that's the problem.  In the main class it's called `http_format_log` but in server.pp it's just `format_log`.

**Comment by hostingnuggets** [comment]
Ahh thank you that was exactly what I was looking for, namely `format_log`. Didn't see anything about it in the docs.

**Comment by alexjfisher** [comment]
BTW, in newer versions of nginx, `log_format` has an `escape` parameter you can set to `json`.  There's no explicit support for this in the puppet module, but that doesn't really matter.
eg just ram it in a bit like (and I haven't got access to my actual code just now)...
```puppet
class { 'nginx':
  log_format =>
    {
      'logstash_json' => 'escape=json \'{ "@timestamp": "$time_iso8601", ...',
    }
}
```

**Comment by alexjfisher** [comment]
@hostingnuggets I'm glad we were able to help.  PRs to improve the docs are always welcome! :)

**Comment by wyardley** [comment]
> Ahh thank you that was exactly what I was looking for, namely format_log. Didn't see anything about it in the docs.

btw, while the main class _does_ need an improvement in parameter docs, location and server resources do actually have mostly-complete docs -- for this case:

https://github.com/voxpupuli/puppet-nginx/blob/master/manifests/resource/server.pp#L101-L106
https://github.com/voxpupuli/puppet-nginx/blob/master/manifests/resource/server.pp#L234

**Comment by hostingnuggets** [comment]
@wyardley cheers for the precisions!
