### ISSUE TITLE
Concat not listet as Requirement in Readme

### ISSUE THREAD

**Issue by jradmacher** [voxpupuli/puppet-nginx#1188]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.x
- Module version: 0.10.0

## How to reproduce (e.g Puppet code you use)
Pupetfile:
`mod 'puppet-nginx', '0.10.0'`

## What are you seeing
Evaluation Error
`Error while evaluating a Resource Statement, Evaluation Error: Resource type not found: Concat`

## What behaviour did you expect instead
working run

## Output log
`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Resource type not found: Concat (file: /etc/puppetlabs/code/environments/development/modules/nginx/manifests/resource/upstream.pp, line: 72, column: 3) (file: /etc/puppetlabs/code/environments/development/modules/nginx/manifests/init.pp, line: 176) on node xxx.ourdomain.com`

**Comment by ekohl** [comment]
We don't list requirements in README since they are listed in ```metadata.json```.

**Comment by rmkellogg** [comment]
The init.pp file does explicitly list puppetlabs-stdlib.  So might suggest this be removed or add additional dependencies.

**Comment by ekohl** [comment]
That is ancient reference. IMHO it's better to remove that.
