### ISSUE TITLE
nginx package spectest failing 

### ISSUE THREAD

**Issue by JacobHenner** [voxpupuli/puppet-nginx#1190]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4, 5
- Ruby: 2.1.9, 2.4.3, 2.5.0
- Distribution: Arch (through spectest)
- Module version: 65b7c743926ea1e434b259a100f7f48d9dbad1ca

## How to reproduce (e.g Puppet code you use)

Execute Travis build against master.

## What are you seeing

rspec is failing, since it expects the package "nginx" to be installed on Arch Linux:

```ruby
else
  it { is_expected.to contain_package('nginx') }
end
```

However, in params.pp, the package_name is masked by override value "nginx-mainline":

```puppet
'ArchLinux': {
      $_module_os_overrides = {
        'pid'          => false,
        'daemon_user'  => 'http',
        'log_group'    => 'log',
        'package_name' => 'nginx-mainline',
      }
    }
```
## Output log

```
Failures:
  1) nginx on archlinux-4-x86_64 nginx::package should contain Package[nginx]
     Failure/Error: it { is_expected.to contain_package('nginx') }
       expected that the catalogue would contain Package[nginx]
     # ./spec/classes/nginx_spec.rb:169:in `block (5 levels) in <top (required)>'
Finished in 9 minutes 11 seconds (files took 19.44 seconds to load)
3457 examples, 1 failure
Failed examples:
rspec ./spec/classes/nginx_spec.rb[1:1:2:1] # nginx on archlinux-4-x86_64 nginx::package should contain Package[nginx]
```

**Comment by JacobHenner** [comment]
Unless I've missed something, it looks like rerunning the Travis build against the current master would result in this failure. Still looking into the cause, since Travis reports that tests of the latest commit succeeded when it was run a few days back.

**Comment by bastelfreak** [comment]
fixed by https://github.com/voxpupuli/puppet-nginx/pull/1191
