### ISSUE TITLE
nginx::service::service_enable does not exist

### ISSUE THREAD

**Issue by fnoop** [voxpupuli/puppet-nginx#1208]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.0
- Ruby: 2.3.3p222
- Distribution: Raspbian (Debian stretch)
- Module version: 0.9.1-rc0

## How to reproduce (e.g Puppet code you use)
```
    class { 'nginx':
        service_manage  => true,
        service_ensure  => $service_ensure,
        service_enable  => $service_enable,
    }
```

## What are you seeing
```
Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Nginx]: has no parameter named 'service_enable' (file: /srv/maverick/software/maverick/manifests/maverick-modules/maverick_web/manifests/nginx.pp, line: 55, column: 5) on node maverick-raspberrylite.home
```

## What behaviour did you expect instead
To control the service at boot

## Any additional information you'd like to impart
Adding the service_enable parameter to index.pp and service.pp makes it behave as expected

**Comment by fnoop** [comment]
Ah sorry I see it's generated from service_ensure.  Most other modules have it as a separately controlled parameter, for consistency and user control would be better as separate, possibly.

**Comment by ekohl** [comment]
@fnoop this should be a small addition and you already know where to make it. Could you come up with a PR to add this?

**Comment by fnoop** [comment]
PR raised
