### ISSUE TITLE
[warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet-nginx#1224]
The `ssl on` syntax is deprecated since nginx 1.15. We should only add it if we use nginx 1.14 or older.

**Comment by PierreR** [comment]
@bastelfreak Could you explain why we use a `fact` to retrieve the `nginx_version` instead of a params defined by the user ? Thanks.

**Comment by bastelfreak** [comment]
Because the fact actually represents the installed version, and not a version a user might want to have. Are you running into any issues with this?

**Comment by PierreR** [comment]
@bastelfreak No issue in particular. Just curious and a bit surprised as I am actually using the module to install `nginx`. In that case it seems a bit weird to have to go to  the machine to check on the installed version.

Thanks for your quick reply !
