### ISSUE TITLE
Reliance on mime.types

### ISSUE THREAD

**Issue by jacksgt** [voxpupuli/puppet-nginx#1240]
Hey there,

excellent puppet module!

However, while experimenting with this module, I have stumbled upon a problem: the module blindly relies on the presence of a `mime.types` files (specifically in https://github.com/voxpupuli/puppet-nginx/blob/0ef72eb7af17a8255dae10ea1eb901b8894a8abf/templates/conf.d/nginx.conf.erb#L69 ). While this will work for most distributions, it does not work when using a custom config directory (`nginx::conf_dir`).

In my case, the configuration gets generated as follows (`nginx.conf`):
```
# MANAGED BY PUPPET
user www-data;
worker_processes 1;
worker_rlimit_nofile 1024;
...
http {

  include       /mnt/etc/nginx/mime.types;
  default_type  application/octet-stream;
  ...
  include /mnt/etc/nginx/conf.d/*.conf;
  include /mnt/etc/nginx/sites-enabled/*;
}
```

Since `/mnt/etc/nginx` was created by the module itself, it is initially empty and therefore lacks `mime.types`.

Upon startup, nginx then complains:
``` nginx -c /mnt/etc/nginx/nginx.conf 
nginx: [emerg] open() "/mnt/etc/nginx/mime.types" failed (2: No such file or directory) in /mnt/etc/nginx/nginx.conf:17
```

**Comment by jacksgt** [comment]
I see two possible ways out of this.

1. Make the mime.type-file path configurable.
2. Include a mime.type-file in this module and ensure it is present at the required location.

I'd prefer the second options, what do you think?

**Comment by ekohl** [comment]
I think the first option is the least invasive one. The mime types file contents could easily go out of date or be different on various distros.

**Comment by martialblog** [comment]
@ekohl I thought about maybe having a simple erb that gets filed with a hash, since the mime types file is rather simple. But yes, there could be variation in distros.

**Comment by jacksgt** [comment]
@martialblog Excellent idea! 
Since the Nginx configuration is managed by this module anyway, I don't think the variations between distros are a problem.

**Comment by martialblog** [comment]
I wrote a little example of a template based solution.

https://github.com/vision-it/puppet-nginx/commit/3a9a68d13cba85c07b3c7907ca0608573474d281
