### ISSUE TITLE
owner/group/mode change, normal?

### ISSUE THREAD

**Issue by ubellavance** [voxpupuli/puppet-nginx#1272]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 5.5.7
- Ruby: ruby-2.0.0.648-33.el7_4.x86_64
- Distribution: RHEL 7
- Module version: 0.15.0

## How to reproduce (e.g Puppet code you use)

My config is actualy very long and I don't think it's relevant, except for the fact that I'm installing the Red hat Software Collections nginx version.

## What are you seeing

```
Notice: /Stage[main]/Nginx::Config/File[/var/opt/rh/rh-nginx114/run/nginx]/owner: current_value 'nginx', should be 'root' (noop)
Notice: /Stage[main]/Nginx::Config/File[/var/opt/rh/rh-nginx114/run/nginx]/group: current_value 'nginx', should be 'root' (noop)
Notice: /Stage[main]/Nginx::Config/File[/var/opt/rh/rh-nginx114/run/nginx]/mode: current_value '0700', should be '0755' (noop)
Notice: /Stage[main]/Nginx::Config/File[/var/opt/rh/rh-nginx114/log/nginx]/mode: current_value '0700', should be '0750' (noop)
Notice: /Stage[main]/Nginx::Config/File[/var/opt/rh/rh-nginx114/lib/nginx/tmp/client_body]/group: current_value 'nginx', should be 'root' (noop)
Notice: /Stage[main]/Nginx::Config/File[/var/opt/rh/rh-nginx114/lib/nginx/tmp/client_body]/mode: current_value '0700', should be '0755' (noop)
Notice: /Stage[main]/Nginx::Config/File[/var/opt/rh/rh-nginx114/lib/nginx/tmp/proxy]/group: current_value 'nginx', should be 'root' (noop)
Notice: /Stage[main]/Nginx::Config/File[/var/opt/rh/rh-nginx114/lib/nginx/tmp/proxy]/mode: current_value '0700', should be '0755' (noop)
```

## What behaviour did you expect instead

I didn't expect this module to change the owner/group/change of files on a freshly installed nginx package from a trusted source.

## Any additional information you'd like to impart

If this is normal, how can I manually specify the owner/group/mode to the module so that I stick with Red Hat's?

**Comment by ekohl** [comment]
This was changed to match the defaults on Debian to avoid a CVE, but in general we should match OS defaults so a patch to change it on RH would be accepted.

**Comment by anarcat** [comment]
i also get this on Debian, FWIW:

```
Notice: /Stage[main]/Nginx::Config/File[/run/nginx/client_body_temp]/mode: mode changed '0700' to '0755'
Notice: /Stage[main]/Nginx::Config/File[/run/nginx/proxy_temp]/mode: mode changed '0700' to '0755'
```

**Comment by anarcat** [comment]
just for the record, i'm not absolutely sure #1443 solves all your concerns, but it's worth giving this a try again, since a lot has changed since 2018...
