### ISSUE TITLE
Is there a way to only create an entry if the cert exists?

### ISSUE THREAD

**Issue by mcblum** [voxpupuli/puppet-nginx#1295]
## How to reproduce (e.g Puppet code you use)
When using Dehydrated and Puppet Nginx, the Nginx config is updated before the cert files are there and Nginx crashes. 

## What behaviour did you expect instead
Not so much expected to see, but wondering if it's possible to check for the required files first, and only if they are there would we created add the Nginx configs.

## Any additional information you'd like to impart
Thank you for working on this package!

**Comment by ekohl** [comment]
I've submitted #1296 which I think would fix it. Can you verify this?

**Comment by mcblum** [comment]
@ekohl woah did you do this for me? That's so kind, thank you. It looks like it would fix it? If I, for example, specify an ssl cert of `/etc/letsencrypt/live/domain.com.pem` or something and then have a location block with `ssl_only => true`, the script would first check if `/etc/letsencrypt/live/domain.com.pem` existed before it would add either the server or location to the Nginx config. Is that correct?

If so, then this is awesome! I'm using Dehydrated and not adding the config would basically make adding a new domain to the proxy and adding a cert for it a 10-15 line process.
