### ISSUE TITLE
Support for Ubuntu 18.04?

### ISSUE THREAD

**Issue by thaiphv** [voxpupuli/puppet-nginx#1307]
Do we have plan to support Ubuntu 18.04?

**Comment by danhart** [comment]
This would be great for us as well 👍

**Comment by mauricemeyer** [comment]
I use the module on Ubuntu 18.04 without problems. It is just not yet added to the metadata so far - maybe there are some integration problems I’ve not seen yet.

**Comment by LongLiveCHIEF** [comment]
There shouldn't be any compatibility issues at all with this module on any Ubuntu 16, 17, or 18 release. As @mauricemeyer said, it's just not in the metadata yet.

In the meantime, if you _do_ run into any issues, go ahead and register an issue as if it was listed as fully supported and we'll take a look at it.

**Comment by Dan33l** [comment]
I am not user of this module, but if your feedback is that it should mainly work, i prefer to declare the module with ubuntu18.04 as supported OS.

@LongLiveCHIEF are you user of the module on 18.04 ?

**Comment by LongLiveCHIEF** [comment]
@Dan33l Yep. 

I just thought we were controlling supported OS's in modulesync_config project.

**Comment by Dan33l** [comment]
The list of files managed by modulesync are listed here:
https://github.com/voxpupuli/modulesync_config/tree/master/moduleroot

The file `metadata.json` is not present and so not managed.

It should be possible:
 * to add OS as supported by the module by updating metadata.json and so with facterdb extend unit tests automatically .
 * to update travis and so run acceptance on 18.04.

If no one sees reason not to add Ubuntu18.04, i can take care of it.

**Comment by Dan33l** [comment]
It looks that acceptance tests catch some not expected items. And so it can not be just update of ̀`medata.json`. Details #1319

Any user of the module can have a look in the failing tests ?
