### ISSUE TITLE
/etc/nginx/conf.d/default.conf still alive

### ISSUE THREAD

**Issue by iglov** [voxpupuli/puppet-nginx#1315]
Hi there!
I have found issue [333](https://github.com/voxpupuli/puppet-nginx/issues/333) where `/etc/nginx/conf.d/default.conf` have been deleted, but now is still alive and i can't find in puppet-nginx manifests way to remove it. Is this possible?

**Comment by alexjfisher** [comment]
By default, I don't think nginx will be configured to read from this directory, but could you see if `confd_purge => true` removes the file for you?

**Comment by iglov** [comment]
Hey, @alexjfisher! Sorry for not answering for a long time, for some reason github haven't send me email notify. Yep, `confd_purge => true` with `server_purge => true` as said here `if (($confd_only and $server_purge) or !$confd_only)` - works good enough.
Thanks for advice! ^_^

**Comment by alexjfisher** [comment]
@iglov No worries. Glad that worked for you.
