### ISSUE TITLE
Syntax error in the 'A more complex proxy example' section of README.md

### ISSUE THREAD

**Issue by jflandry** [voxpupuli/puppet-nginx#1390]
There is a stray semicolon in an example.
`'localhost:3002': => {` should be `'localhost:3002' => {`

## Affected Puppet, Ruby, OS and module versions/distributions

- Module version: master branch

## How to reproduce (e.g Puppet code you use)
```
puppet parser validate /tmp/typo.pp
Error: Could not parse for environment production: Syntax error at ':' (file: /tmp/typo.pp, line: 13, column: 21)

cat /tmp/typo.pp 
nginx::resource::upstream { 'puppet_rack_app':
  members => {
    'localhost:3000' => {
      server => 'localhost',
      port   => 3000,
      weight => 1,
    },
    'localhost:3001' => {
      server => 'localhost',
      port   => 3001,
      weight => 1,
    },
    'localhost:3002': => {
      server => 'localhost',
      port   => 3002,
      weight => 2,
      },
  },
}

nginx::resource::server { 'rack.puppetlabs.com':
  proxy => 'http://puppet_rack_app',
}
```

**Comment by ghoneycutt** [comment]
Thanks for pointing this out! Could you please send a pull request. This can be done entirely through the browser - https://github.com/voxpupuli/puppet-nginx/edit/master/README.md

**Comment by jflandry** [comment]
For reference: https://github.com/voxpupuli/puppet-nginx/pull/1391
