### ISSUE TITLE
mailhost resource does not use ensure parameter, therefore cannot be made absent

### ISSUE THREAD

**Issue by qs5779** [voxpupuli/puppet-nginx#1394]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: all
- Ruby: all
- Distribution: all
- Module version: i assume all, but only verified with latest/master

## How to reproduce (e.g Puppet code you use)
define a mailhost resource using defaults, change ensure to absent

## What are you seeing
The configuration file for the mailhost resource is not removed

## What behaviour did you expect instead
I expected it to be removed

**Comment by alexjfisher** [comment]
Adding `skip-changelog` label so we don't get 2 almost identical entries appear. (one for the issue, one for the PR).
