### ISSUE TITLE
Support hybrid RSA and ECDSA configuration

### ISSUE THREAD

**Issue by ltning** [voxpupuli/puppet-nginx#1434]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: Any
- Ruby: Any
- Distribution: Any
- Module version: Any

## How to reproduce (e.g Puppet code you use)
Attempt to specify more than one ssl_certificate_key and ssl_certificate/chain/fullchain fails.

## What are you seeing
Attempting to specify more than one ssl_certificate_key and ssl_certificate/chain/fullchain fails.

## What behaviour did you expect instead
These parameters should be Boolean|String|Array rather than the current Boolean|String, and create one ssl_* configuration line for each entry in the array.

## Any additional information you'd like to impart
https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_certificate

**Comment by Azylog** [comment]
Hello,
I've also been limited by this setting : we have to choose between RSA and ECC certificates, despite the Nginx's ability to support both in the same vhost.

Having this supported would be a nice addition

**Comment by saz** [comment]
As I'm also affected by that issue, I'm currently working on a PR.
I hope to get it done today and happy about any feedback
