### ISSUE TITLE
Install only package NGINX. Is it possible? 

### ISSUE THREAD

**Issue by alexkorotysh** [voxpupuli/puppet-nginx#1464]
Hi everyone, could you please share if is it possible install only nginx without configuration nginx.conf

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.21.1
- Ruby: ruby 2.4.7p357 (2019-08-28 revision 67796) [x86_64-linux]
- Distribution: Ubuntu 20
- Module version: mod 'puppet-nginx', :latest

**Comment by ghoneycutt** [comment]
No, that's not the aim of the module. If you really just want to install a package, suggest using a resource such as below in your nginx profile.

```puppet
package { 'nginx':
  ensure => 'present',
}
```
