### ISSUE TITLE
New Release / Puppet Forge Release (Question)

### ISSUE THREAD

**Issue by basti-nis** [voxpupuli/puppet-nginx#1495]
Hey Contrib's,

is there a plan to release a new version and also on puppet forge in the near future?

We run sometimes into the "/run/nginx/client_body_temp"-problem which will be solved with these commit:
https://github.com/voxpupuli/puppet-nginx/commit/f52fb7c1c009aad27219f0134b6085fd02287350

Would appreciate it!

kind regards

**Comment by danir-de** [comment]
Having problems with this here too. Maybe this would help?
We've used the systemd workaround from [1372#issuecomment-812332997](https://github.com/voxpupuli/puppet-nginx/issues/1372#issuecomment-812332997) in the meantime.
