### ISSUE TITLE
Allow puppetlabs-concat 8

### ISSUE THREAD

**Issue by hadmut** [voxpupuli/puppet-nginx#1553]
- Puppet: 7
- Ruby: none
- Distribution: ubuntu 20.04
- Module version: 4.4.0

Since puppet labs do not maintain their docker image anymore, I started to create my own puppet server docker image with Ubuntu 20.04 and the original puppetlabs packages (they do not fully support 22.04). 

I noticed that I cannot install the module puppet-nginx with taking latest modules (without explicitely selecting older versions):

Error: Could not install module 'puppet-nginx' (v4.4.0)
  The requested version cannot satisfy one or more of the following installed modules:
    puppetlabs-concat, installed: 8.0.1, expected: >= 4.1.0 < 8.0.0

So puppet-nginx cannot be installed with the current latest modules. 

The question is: would puppet-nginx be working with concat 8.0.1, or would it be necessary to intentionally install an older version of puppetlabs-concat?

regards

**Comment by kenyon** [comment]
It likely works fine with newer puppetlabs-concat. Create a pull request increasing the version boundary, and if the tests all pass, then it's good.

**Comment by kenyon** [comment]
Done in #1558.
