### ISSUE TITLE
Add uwsgi_pass

### ISSUE THREAD

**Issue by Atlantic777** [voxpupuli/puppet-nginx#160]
Hi! It would be nice to have uwsgi_pass, too. It's very similar to proxy_pass except uwsgi params have to be included and maybe some more properties are needed.

Here's example how I use it (a block from nginx conf):

    location / {
        include uwsgi_params;
        uwsgi_pass localhost:38001;
        uwsgi_modifier1 30;
    }

**Comment by wyardley** [comment]
I'm going to close this one, since there was no further response.
The feature does now exist as of June 2014, though the param in location resource is 'uwsgi' vs. 'uwsgi_pass', 
https://github.com/voxpupuli/puppet-nginx/commit/2778df07fbdcc65485f580d9a092ec121b1a87d8
