### ISSUE TITLE
Catch all requests with wrong host and return 444 status

### ISSUE THREAD

**Issue by seocam** [voxpupuli/puppet-nginx#261]
For security and cleanness reasons it's a good practice to deny requests without host or with hosts not configured in any vhost.

Nginx provides a pretty easy and simple way to that:

```
server {
    listen      80;
    server_name "";
    return      444;
}
```
Reference: http://nginx.org/en/docs/http/request_processing.html#how_to_prevent_undefined_server_names

So far I couldn't find a way to do that with this module. 

I can implement that and send a pull request but I'd to discuss what's the best approach to get this done.

**Comment by wyardley** [comment]
I don't think it's a given that most people want a default vhost to return 4XX, depends on whether it's a system with many virtualhosts or just one (default), in which case one may very well _want_ requests without a matching host to still hit that default vhost. I think the module does give the ability to configure things as you describe.

#888 does allow suppressing the error_log directive by setting it to 'absent'.

I'm going to close this one for now.

**Comment by cdosborn** [comment]
I stumbled upon this and wanted to correct something small:
> For security and cleanness reasons it's a good practice to deny requests without host or with hosts not configured in any vhost.

Setting `server_name` to `""` only matches the request without a Host header, it does *not* serve as a fallback.
