### ISSUE TITLE
A redirect-only vhost

### ISSUE THREAD

**Issue by xaque208** [voxpupuli/puppet-nginx#370]
We're in the process of evaluating this module instead of our own for various reasons, but I am having trouble reproducing a config that we use pretty commonly.  I'm willing to add support if it turns out thats required, but I thought I'd ask if there was a clean way to do this with the module in its current form.

First, here is the resulting vhost I am trying to produce.

```
server {
  listen   *:80;
  server_name sitea.example.com;
  rewrite ^/(.*) http://siteb.example.com/$1 permanent;
}
```

So here there are no locations, no other resources, just receive requests on `sitea.example.com` and redirect them to `siteb.example.com`.  Pretty simple.

Now the manifest I tried to work out to do this.

``` Puppet
  nginx::resource::vhost { 'sitea.example.com':
    use_default_location => false,
    index_files          => [],
    location_custom_cfg  => {},
    rewrite_rules        => [
      '^/(.*) http://siteb.example.com/$1 permanent',
    ],
  }
```

I'm willing to suspend my annoyance at the lack of brevity required here, but this doesn't do what I need, since the `rewrite_rules[]` only exists within the `location` blocks.  Nginx supports the ability to have rewrite rules in the server blocks, so it seems to me that the module should also support this.

Is there a way that those more experienced with this module can think of to produce the desired state with what exists today?  If so, how?  If not, what would be the best approach I could take to add support?

I was thinking some kind of `rewrite_only` for `nginx::resource::vhost`, but from what I can tell that class seems to revolve around a location based server resource block.

Any insight would be appreciated.

Cheers.

**Comment by tim-massey** [comment]
Thanks, works for me.

**Comment by khaefeli** [comment]
I think this rewrite solutions are bad at all.
see: http://wiki.nginx.org/Pitfalls

why not providing a nginx::ressource::vhost with a scheme 301 redirect?

    server {
      server_name www.domain.com;
      return 301 $scheme://domain.com$request_uri;
    }

or:

     return 301 http://domain.com$request_uri;

instead of:

    rewrite ^/(.*)$ http://domain.com/$1 permanent;

**Comment by levilovelock** [comment]
I also want something like @khaefeli is suggesting. Any updates on providing this?

**Comment by joshuagordondba** [comment]
I have done this unfortunately, I am not at work but hope to remember to
update this on Monday. It was not east to figure out perhaps this should be
added as an option.

**Comment by j4ybee** [comment]
@joshuagordondba it's Monday today, even though a few month later ;) , so I wanted to send a little reminder as I am very interested in your solution!

**Comment by bernhardjt** [comment]
What do you think of https://github.com/jfryman/puppet-nginx/pull/774 ?

**Comment by wyardley** [comment]
Sorry for the lack of discussion / merge for this. I will comment in #774

**Comment by wyardley** [comment]
It would be nice to have the way to do a return and suppress the rest of the configs in the vhost, similar to what we do with the SSL rewrite or when `ssl_only` is set....

**Comment by NimishKmr** [comment]
Hello,
Do we have a solution for this. I am need of this as we have to redirect our old site to new site. And my nginx puppet config is a bit complex. We have multiple websites and we have manifest files where we provide server_name, port, mage_run_code, etc. I would like to add redirect/rewrite rule in this manifest for a particular site. How to achieve this?

**Comment by h0tw1r3** [comment]
Solution with puppet/nginx 1.0.0:

```
nginx::resource::server { "somewhere.old":
    maintenance => true,
    maintenance_value => 'return 301 $scheme://somewhere.new$request_uri',
}
```

**Comment by ekohl** [comment]
Thanks!
