### ISSUE TITLE
proxy_redirect default value

### ISSUE THREAD

**Issue by keymone** [voxpupuli/puppet-nginx#395]
i'm not sure what is the rationale behind making default value for `proxy_redirect` `off` but it is different from default value `default` used by nginx itself when the option is not present in config file. http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_redirect

also it looks like default value in params.pp was `undef` and option was omitted unless a non-nil value was passed - was there a reason to change that?

**Comment by wyardley** [comment]
I agree that more values should just be set to undef (to allow them to get the default setting). I'm not sure why config.pp has it default to 'off'. 

@3flex @bastelfreak: anyone object to switching it to either 'undef' or 'on'?

**Comment by wyardley** [comment]
Better late than never, I guess?
Seems like as good a place as any for the 'start making certain values default' (#896) changes...
#948
