### ISSUE TITLE
Hiera does not merge correctly

### ISSUE THREAD

**Issue by jg-development** [voxpupuli/puppet-nginx#426]
I have a hiera file with the following data:

```
:hierarchy:
    - "%{::environment}"
    - webserver/hosts/foo.local
    - webserver/hosts/bar.local
```

And 2 yaml files with the following code:

```
nginx::nginx_vhosts:
  'foo.local:
    ensure: 'present'
    listen_port: '80'
    listen_ip: '*'
    index_files: ['index.php']
    www_root: "/var/www/foo.local"
    server_name: ['foo.local']
    use_default_location: false
```

and 

```
nginx::nginx_vhosts:
  'bar.local:
    ensure: 'present'
    listen_port: '80'
    listen_ip: '*'
    index_files: ['index.php']
    www_root: "/var/www/bar.local"
    server_name: ['bar.local']
    use_default_location: false
```

the hiera command " hiera -c hiera.yaml -h nginx::nginx_vhosts"
gives me the correct result... a merge from the two vhosts and files

```
{"foo.local"=>
  {"ensure"=>"present",
   "listen_port"=>"80",
   "listen_ip"=>"*",
   "index_files"=>["index.php"],
   "www_root"=>"/var/www/foo.local",
   "server_name"=>["foo.local"],
   "use_default_location"=>false},
 "bar.local"=>
  {"ensure"=>"present",
   "listen_port"=>"80",
   "listen_ip"=>"*",
   "index_files"=>["index.php"],
   "www_root"=>"/var/www/bar.local",
   "server_name"=>["bar.local"],
   "use_default_location"=>false}}
```

But only the first vhost is installed on the system, the second is ignored. I used the multiple files with multiple hashs with other modules and this problem seems to be only with the nginx module.

Greetings Jan

**Comment by richard-kti** [comment]
What was the bug (link, etc?)
I am having the same issue and searching got me here.

**Comment by dene14** [comment]
I did experienced the same issue some time ago, it has became even more confusing when I started to fix "deprecation notice" about direct parameters assignment to class {"nginx":}. So I've done it with a following code in my "nginx_base" profile:

class site::profiles::nginx_base (
    $nginx_vhosts    = hiera_hash('nginx::nginx_vhosts', {}),
    $nginx_upstreams = hiera_hash('nginx::nginx_upstreams', {}),
    $nginx_locations = hiera_hash('nginx::nginx_locations', {}),
    $http_cfg_append = hiera_hash('nginx::config::http_cfg_append', {}),
) {

############### Some magic to autoconfigure collect::plugin::nginx ###############
  $status_location = "${nginx_locations['stub_status']['location']}"
  $status_vhost    = "${nginx_locations['stub_status']['vhost']}"
  $status_hostname = "${nginx_vhosts[$status_vhost]['server_name'][0]}"
  $status_port     = "${nginx_vhosts[$status_vhost]['listen_port']}"
  $status_url      = "http://${status_hostname}:${status_port}${status_location}"
##################################################################################


  class {'nginx::config':
    http_cfg_append => $http_cfg_append,
    # expand by parameters which require hash's deep merge
  }

  class {'nginx':
    nginx_vhosts    => $nginx_vhosts,
    nginx_upstreams => $nginx_upstreams,
    nginx_locations => $nginx_locations,
    # expand by parameters which require hash's deep merge
  }
  ->
  class { 'collectd::plugin::nginx':
    url => "$status_url"
  }
  ->
  Class['site::profiles::nginx_base']
}

You can adjust hiera lookups as needed (for priority lookups). However, I'd like to hear some notes from maintainers whether I did it right or wrong.
