### ISSUE TITLE
Any way to specify multiple listening ports?

### ISSUE THREAD

**Issue by pablokbs** [voxpupuli/puppet-nginx#433]
I'm trying to create a vhost like this:

```
server {
    listen 80 default_server;
    listen 81;
```
But the listen_port value must be an integer, is there a way I can specify 2 (or more) listening ports to a vhost without the need to duplicate the vhost?

Thanks, great module.

**Comment by wyardley** [comment]
I'm going to close this, since there doesn't seem to have been a PR, it's been quite some time, and there is a workaround mentioned.
