### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by jfryman** [voxpupuli/puppet-nginx#436]
Something to consider one of these days...

**Comment by wyardley** [comment]
I think this is a great idea, but guessing it's not going to happen until someone with the need for it adds a PR?

@bastelfreak @3flex: proposing we table this one for now?

**Comment by 3flex** [comment]
Other than this issue, I don't think there's been any demand for native Windows support, so I agree it can be closed until someone decides to take a look at it again.

Might also want to consider waiting until nginx says Windows support is production ready (if that ever happens) before revisiting.

**Comment by feltra** [comment]
Basically got it working using:
        class { 'nginx':
          manage_repo           => false,
          stream                => true,
          sites_available_group => $group,
          sites_available_owner => $owner,
          sites_available_mode  => '0770',
          global_owner          => $owner,
          global_group          => $group,
          global_mode           => '0770',
          log_group             => $group,
          log_user              => $owner,
          log_mode              => '0770',
          daemon_user           => $owner,
          daemon_group          => $group,
          root_group            => $group,
          pid                   => "${nginxroot}/nginx-1.15.8/temp",
          temp_dir              => 'C:/Windows/temp',
          run_dir               => "${nginxroot}/nginx-1.15.8/html",
          conf_dir              => "${nginxroot}/nginx-1.15.8/conf",
          log_dir               => "${nginxroot}/nginx-1.15.8/logs",
          client_body_temp_path => "${nginxroot}/nginx-1.15.8/temp/client_body_temp",
          proxy_temp_path       => "${nginxroot}/nginx-1.15.8/temp/proxy_temp",
        }
I have installed nginx using the chocolatey module and managing the service with nssm module =)
There is a few things to adjust.. 

Headsup for @bastelfreak

**Comment by feltra** [comment]
I will doing some tests.. since my first use case is for proxying.. Im using nginx::resource::streamhost and nginx::resource::server
