### ISSUE TITLE
Should fail compilation when default location created for vhost without other required parameters

### ISSUE THREAD

**Issue by 3flex** [voxpupuli/puppet-nginx#447]
When `vhost` resource is created a default location is automatically created for the vhost by default. However, if the user hasn't set `www_root`, `proxy`, `fastcgi`, or `location_custom_cfg` configuration on the vhost as well the location will be created with an invalid configuration.

There should be an error message in this case so the user knows what to do. See #446

**Comment by wyardley** [comment]
This error does now exist.
