### ISSUE TITLE
proxy_set_header does not support X-Forwarded-Proto and X-Forwarded-Port

### ISSUE THREAD

**Issue by epicwhale** [voxpupuli/puppet-nginx#476]
```
location_custom_cfg => {
    'proxy_set_header' => {
      'X-Real-IP'         => '$remote_addr',
      'X-Forwarded-For'   => '$proxy_add_x_forwarded_for',
      'X-Forwarded-Proto' => 'https',
      'X-Forwarded-Port'  => '443',
      'Host'              => '$host'
    },
  }
```

Doing the above, removes the X-Forwarded-Proto and X-Forwarded-Port headers.

Is it because its missing here? 
https://github.com/jfryman/puppet-nginx/blob/master/data/common.yaml#L26

**Comment by supernovae** [comment]
I have same problem, the above config pattern worked for me though..

**Comment by tizzo** [comment]
It's worth noting the above configuration pattern won't help you if you need to differentiate any two vhosts and have some proxies have certain headers and not others…

**Comment by sabretus** [comment]
For me it works like this perfectly fine:

```ruby
  include nginx
  
  nginx::resource::vhost { "${domain}-ssl":
    server_name           => [ "${domain}" ],
    listen_port           => 443,
    proxy                 => $proxy_host,
    proxy_set_header      => [
      'X-Real-IP         $remote_addr',
      'X-Forwarded-For   $proxy_add_x_forwarded_for',
      'X-Forwarded-Proto https',
      'X-Forwarded-Port  443',
      'Host              $host' 
    ],
    ssl                   => true,
    ssl_cert              => "${cert_path}",
    ssl_key               => "${key_path}",
  }
```

And I could define my module as many times as needed

**Comment by wyardley** [comment]
Is anyone still seeing this problem as of now (with a recent version of the module? I have tested this recently and worked for me as expected, so I'm going to close this for now.
