### ISSUE TITLE
fastcgi_param https

### ISSUE THREAD

**Issue by AlmogBaku** [voxpupuli/puppet-nginx#492]
Is there any way to add the `fastcgi_param https on` by the location resource?
The problem is that this is changed between the version of the vhost.

See example here http://wiki.nginx.org/Symfony

**Comment by 3flex** [comment]
You can use `location_cfg_prepend` or `location_cfg_append` to add your own directives to the location. There's currently no way to do this with a specific parameter unfortunately.

**Comment by wyardley** [comment]
This is now supported, FWIW. I'm going to close this one.
