### ISSUE TITLE
Issues with fastcgi_params

### ISSUE THREAD

**Issue by vincentbernat** [voxpupuli/puppet-nginx#499]
Hi!

The shipped `fastcgi_params` file is not generic enough. It would be nice to change `SCRIPT_FILENAME` to `$document_root$fastcgi_script_name` for better flexibility. However, this change may be disruptive. This is how the file shipped with nginx is.

Currently, `SCRIPT_FILENAME` is not correct for many setup and it may not be overridable because the order of the `fastcgi_param` directives are important. For stuff like `php-fpm`, the last entry wins, so it is easy to override `SCRIPT_FILENAME`. However, for `fcgiwrap`, this is the first one that will win.

**Comment by lesinigo** [comment]
I've been bitten by exactly this issue. Trying to find out why a setup with `fcgiwrap` did not work, I've found that my `SCRIPT_FILENAME` (from `fastcgi_param`) was being ignored in favor of the one included in the file referenced from `fastcgi_params`.  As referenced in #682, the only workaround at the moment is to create and reference an empty file for `fastcgi_param`.

**Comment by wyardley** [comment]
I'm going to close this; please follow #862 to keep track of resolution of this.
