### ISSUE TITLE
Multiple listen ip addresses (v4 and/or v6)

### ISSUE THREAD

**Issue by mechanicalduck** [voxpupuli/puppet-nginx#515]
Being able to specify multiple ip addresses (for v4 and/or v6) 
for all the different nginx resources (e.g. vhost).

````
nginx::resource::vhost { 'domain.tld':
  listen_ip   => [  '192.168.100.1', '192.168.200.1', ],
}
````

Related to request for multiple ports: https://github.com/jfryman/puppet-nginx/issues/433

**Comment by wyardley** [comment]
It looks like listen_ip and ipv6_listen_ip can both be arrays now.
