### ISSUE TITLE
Manage_repo is missing in nginx::config

### ISSUE THREAD

**Issue by PierreR** [voxpupuli/puppet-nginx#535]
I am setting "manage_repo" to false like this:
```
class { 'nginx':
  manage_repo => false,
}
```
I have got a deprecation warning that encourages me to use hiera instead but `nginx::config::manage_repo` does not seem to exist.

Should I submit a PR to add it ?

**Comment by wyardley** [comment]
I'm going to close this, since it hasn't had any comments since 2014, and has not had any updates since 'needs info' was set in April of 2015.

FWIW, I haven't seen this.
