### ISSUE TITLE
Get more friendly with concat

### ISSUE THREAD

**Issue by jfryman** [voxpupuli/puppet-nginx#538]
>As an aside I think we should move away from these methods to insert custom code into the manifests, and promote puppetlabs-concat as the best way to do this since it allows for total customization of any code that will be added to the vhost/location.

Want to capture a comment from @3flex here https://github.com/jfryman/puppet-nginx/pull/532#issuecomment-68370797 to track for a later day. :grin:

**Comment by wyardley** [comment]
I think we are now friendly with concat. 😉
