### ISSUE TITLE
Default params problem

### ISSUE THREAD

**Issue by pcfreak30** [voxpupuli/puppet-nginx#554]
Getting a weird issue.

`Error: Could not retrieve catalog from remote server: Error 400 on SERVER:  is not valid. It should be 4 digits (0644 by default). at /etc/puppet/environments/production/modules/nginx/manifests/resource/vhost.pp:412`

`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: "" is not an Array.  It looks to be a String at /etc/puppet/environments/production/modules/nginx/manifests/resource/location.pp:206`

This is in v0.0.10+. If I jump to v0.0.9 it works. Any ideas as to what change caused this? Also know I have only included the nginx class, but no manifest actually uses it.

Agent and Master Version: 3.7.3

**Comment by jamescarr** [comment]
I have been getting this as well, same setup.

**Comment by 3flex** [comment]
@pcfreak30 @jamescarr which specific version of the module are you using? You say "v0.0.10+" but can you specify which exact version you're using?

**Comment by samchang-iit** [comment]
I was also getting the same error for the mode, but setting it in hiera removed the error and when i remove from hiera it didn't come back right away.

I'm now getting the same 2nd error with "" is not an Array on location.pp:206.

on Oracle Linux with SELinux. 3.6.2 (Puppet Enterprise 3.3.2) and using jfryman/nginx-0.2.6

**Comment by samchang-iit** [comment]
Ok, after looking at https://github.com/jfryman/puppet-nginx/issues/566 it was just some issue loading the proper nginx module.

when i changed 'include nginx' to 'include ::nginx' has resolved all the loading issues
