### ISSUE TITLE
Hiera documentation bug

### ISSUE THREAD

**Issue by jowrjowr** [voxpupuli/puppet-nginx#556]
The workaround described here https://github.com/jfryman/puppet-nginx/blob/master/docs/hiera.md in regards to specifying nginx::config options without using hiera does not work.

Including nginx will construct the nginx::config class, which then errors out when you later construct it because nginx::config will be duplicated.

My preferred solution is this:

class { 'nginx::config': }-> class { 'nginx': }

This enforces the proper ordering, and eased a bit of frustration I was having.

**Comment by jfryman** [comment]
Thanks @jowrjowr. What would you change to make this actionable for new users? Docs need updating, or is this better a code change in your opinion?

**Comment by jowrjowr** [comment]
I think it needs to be made explicit that if you specify a nginx::config,
you have to fully populate it because the module won't merge in other
defaults.

It would be really nice if folks weren't pushed so strongly into hiera. Why
not just construct nginx::config as a normal class, and allow parameters to
be overrided as needed?

**Comment by jfryman** [comment]
> It would be really nice if folks weren't pushed so strongly into hiera. Why
not just construct nginx::config as a normal class, and allow parameters to
be overrided as needed?

It's not a push. I'm really trying to find a nice medium between those that do use hiera, and those that do not. We're sitting on two worlds here... and it seems to be difficult to truly find that.

The ideal is that what I do specify in the documents does work, and you do not have to fully populate `nginx::config`. That just means there is more work to be done.

**Comment by devopsdevon** [comment]
For anyone that stumbles across this issue and needs a temporary work around, here is a fully functional example of instantiating nginx::config manually using version 0.2.2 of the nginx module.

As far as I can tell, this example sets all of the same defaults that would normally get set (skipping over anything set to undef by default):

```
  include ::nginx::params
  class { '::nginx::config':
    client_body_temp_path          => $::nginx::params::client_body_temp_path,
    conf_dir                       => $::nginx::params::conf_dir,
    daemon_user                    => $::nginx::params::daemon_user,
    global_owner                   => $::nginx::params::global_owner,
    global_group                   => $::nginx::params::global_group,
    global_mode                    => $::nginx::params::global_mode,
    http_access_log                => $::nginx::params::http_access_log,
    log_dir                        => $::nginx::params::logdir,
    nginx_error_log                => $::nginx::params::nginx_error_log,
    pid                            => $::nginx::params::pid,
    proxy_temp_path                => $::nginx::params::proxy_temp_path,
    sites_available_owner          => $::nginx::params::sites_available_owner,
    sites_available_group          => $::nginx::params::sites_available_group,
    sites_available_mode           => $::nginx::params::sites_available_mode,
    super_user                     => $::nginx::params::super_user,
    temp_dir                       => $::nginx::params::temp_dir,
  } -> class { '::nginx': }
```

**Comment by 3flex** [comment]
@jowrjowr does this documentation update help? https://github.com/jfryman/puppet-nginx/pull/669

**Comment by wyardley** [comment]
We are going to be reworking this, and probably flattening things out. So, I'm going to close this ticket for now, feel free to follow #950
