### ISSUE TITLE
Defining vhosts in Hiera

### ISSUE THREAD

**Issue by stevelacey** [voxpupuli/puppet-nginx#566]
I am probably just doing Hiera wrong... but this does nothing for me:

hiera/common.yaml:

```yaml
---
nginx::config::worker_processes: "%{::processorcount}"

nginx::nginx_vhosts:
  "%{::fqdn}":
    www_root: "/var/www/%{::fqdn}"
```

In my node:

```puppet
include nginx
include nginx::config
```

I think the Hiera is at least right my worker_processes gets set, and the following is returned if I run this on the master:

```
hiera -c /etc/puppet/current/hiera.yaml nginx::nginx_vhosts ::fqdn=test 
=> {"test"=>{"www_root"=>"/var/www/test"}}
```

Do I need to define something specific to the vhost or vhosts in general in my manifest to trigger it pulling in the vhost settings? `nginx::resource::vhost { $::fqdn: }` moans about no params passed – i.e. it can't see the `www_root`.

![jennifer-lawrence-shrugging-gif](https://cloud.githubusercontent.com/assets/289531/6097348/07352226-afb3-11e4-9909-1a54de06d2ba.gif)

**Comment by stevelacey** [comment]
So either I am missing the point, or you have to do this:

```puppet
  class { "::nginx":
    geo_mappings          => hiera("nginx::geo_mappings", {}),
    string_mappings       => hiera("nginx::string_mappings", {}),
    nginx_locations       => hiera("nginx::nginx_locations", {}),
    nginx_mailhosts       => hiera("nginx::nginx_mailhosts", {}),
    nginx_upstreams       => hiera("nginx::nginx_upstreams", {}),
    nginx_vhosts          => hiera("nginx::nginx_vhosts", {}),
    nginx_vhosts_defaults => hiera("nginx::nginx_vhosts_defaults", {}),
  }

  include nginx::config
```

Either I am doing things wrong, and if so, please correct me… or seriously, document this, in the README, or hiera doc file, in big ass letters.

I assume these aren't the defaults as it would cause hiera-less users errors?

**Comment by samchang-iit** [comment]
I seem to have had something similar, and i fixed it by changing
include nginx
to
include ::nginx

**Comment by wyardley** [comment]
@stevelacey: is this still a problem, or can we close this out?

**Comment by stevelacey** [comment]
I don't use Puppet anymore, so it's not a problem for me at least 😉
