### ISSUE TITLE
Cannot set both location_alias and fastcgi at the same time on a location

### ISSUE THREAD

**Issue by alex-barylski** [voxpupuli/puppet-nginx#591]
I have the following:

```
  nginx::resource::vhost { 'aerospace':
    ensure                => present,

    www_root              => '/usr/share/nginx/html',
    server_name           => ['apps.cadorath.local'],

    index_files           => ['index.php', 'index.html'],

    fastcgi     => 'unix:/var/run/php5-fpm.sock',
  }

  nginx::resource::location { 'application':
    vhost => 'aerospace',

    ensure  => present,
    location => '~ [^/]\.php(/|$)',
    location_alias => '/usr/share/nginx/html/application',

    fastcgi_split_path => '^(.+>\.php)(/.*)$',
    fastcgi_param  => {
      'MYDOMAIN_FQDN' => 'http://apps.mydomain.local',
    }
  } 
```

This is the resulting file in .../sites-enabled

```
server {
  listen *:80;
  server_name           apps.cadorath.local;

  set $maintenance "off";
  if ($maintenance = "on") {
      return 503;
  }
  index  index.php index.html;

  access_log            /var/log/nginx/aerospace.access.log combined;
  error_log             /var/log/nginx/aerospace.error.log;

  location ~ [^/]\.php(/|$) {
    alias /usr/share/nginx/html/application;
  }

  location / {
    root          /usr/share/nginx/html;
    include       /etc/nginx/fastcgi_params;

    fastcgi_pass  unix:/var/run/php5-fpm.sock;
  }
}
```

Why is split_path and param not being echo'ed to the resulting file -- no errors as far as I can tell. What am I missing???

Alex

**Comment by 3flex** [comment]
Hi @alex-barylski 

You're not doing anything wrong here, the module doesn't currently support this (but a PR to improve things here would definitely be appreciated!)

The relevant code is here: https://github.com/jfryman/puppet-nginx/blob/master/manifests/resource/location.pp#L323-L336

You've specified both `location_alias` and `fastcgi` for your location, and `location_alias` is taking precedence when the module selects a template to render for the location block.

In the meantime you can use `location_alias` then set your fastcgi parameters using `location_cfg_prepend` and/or `location_cfg_append` or similar.

**Comment by alex-barylski** [comment]
I would love to help...unfortunately I am totally new to Puppet so I doubt I could contribute anything of value -- just questions for now :) I will try your suggested solution -- thank you for the quick response.

**Comment by 3flex** [comment]
Let's leave this open. It's still a valid issue even if you're not up to submitting a PR to address it!

**Comment by alex-barylski** [comment]
I have another issue with the alternative you offered:

```
      'fastcgi_param' => 'MYDOMAIN_APP_SMTP_USER ""',
      'fastcgi_param' => 'MYDOMAIN_APP_SMTP_PASS ""',

      'fastcgi_param' => 'MYDOMAIN_APP_DB_USER "apps"',
      'fastcgi_param' => 'MYDOMAIN_APP_DB_PASS "XXX"',
      'fastcgi_param' => 'MYDOMAIN_APP_DB_HOST "localhost"',

      #
      # ERP/RPI router relies on PATH_INFO so we fudge the value in NGINX to emulate Apache?
      'set'           => '$path_info $fastcgi_path_info',
      'fastcgi_param' => 'PATH_INFO $path_info',
```

I finally got this to go without error but when I view the *.conf file I see only the last fastcgi_param PATH_INFO $path_info, like:

```
server {
  listen *:80;
  server_name           apps.mydomain.local;

  set $maintenance "off";
  if ($maintenance = "on") {
      return 503;
  }
  index  index.php index.html;

  access_log            /var/log/nginx/aerospace.access.log combined;
  error_log             /var/log/nginx/aerospace.error.log;

  location ~ [^/]\.php(/|$) {
    alias unix:/var/run/php5-fpm.sock;
    fastcgi_param PATH_INFO $path_info;
    set $path_info $fastcgi_path_info;
  }

  location / {
    root      /usr/share/nginx/html;
  }
}
```

Its like a associative array is used instead of a stack and the hashkey 'fastcgi_param' is over written each iteration -- any ideas???

Should I open another ticket on this matter?

**Comment by wyardley** [comment]
#966 and #970 are a step in the right direction here, and I _think_ #970 may allow this, specifically in https://github.com/voxpupuli/puppet-nginx/blob/master/templates/vhost/location.erb#L2-L7

If this is still an issue, or if you have time, @alex-barylski, could you try testing current git master and see if the behavior is more along the lines of what you were thinking? We'll be cutting a release soon as well.

**Comment by wyardley** [comment]
I believe this should be fixed, since no one has tested / verified still, I'm going to close this for now, let's open a new issue if there are additional problems, though I would like to do a better rework of this logic at some point.
