### ISSUE TITLE
How to insert conditionals into location

### ISSUE THREAD

**Issue by vchepkov** [voxpupuli/puppet-nginx#617]
An example how to configure Wordpress on nginx https://codex.wordpress.org/Nginx includes several fragments I am not sure how to implement using this module
Particularly, this block inside location

```
	if (!-f $document_root$fastcgi_script_name) {
		return 404;
	}
```

Thanks

**Comment by visibilityspots** [comment]
@vchepkov take a look at https://github.com/jfryman/puppet-nginx/issues/308 it explained it for me. 

We could consider to enhance it into the README file perhaps..

**Comment by wyardley** [comment]
Docs fixes gratefully appreciated; that said, I'm going to close this for now, since it's been quite a while since this was opened.
