### ISSUE TITLE
Specifying `keepalive` and `least_conn` in `upstream` gives warning.

### ISSUE THREAD

**Issue by IslandUsurper** [voxpupuli/puppet-nginx#641]
nginx would prefer that directives like `ip_hash` and `least_conn` would come before `keepalive` in an `upstream` section. But sorting the keys of `$upstream_cfg_prepend` makes that problematic.

It's only a warning, so it's only annoying as opposed to something more serious, but it would be good not to have it show up.

**Comment by wyardley** [comment]
Having both `upstream_cfg_append` and `upstream_cfg_prepend` now (#953) may help a bit (you could use append only for the keepalive, but that seems kind of hackish); I can see if we can do something similar to 
https://github.com/voxpupuli/puppet-nginx/blob/master/templates/vhost/vhost_header.erb#L91
if it helps, though of course if you put keepalive in the prepend and then something else in append, it will go after.

**Comment by wyardley** [comment]
@IslandUsurper btw, can you include an example that will generate the config w/ the warning?

**Comment by wyardley** [comment]
#969 should address this.
