### ISSUE TITLE
Same location on multiple vhosts

### ISSUE THREAD

**Issue by MasterMind2k** [voxpupuli/puppet-nginx#644]
Hi.

I would like to have one site on several domains with every domain with it's own certificate. With current version, I have to duplicate all locations for every vhost.

It would then (probably) look something similar to:

```
'/':
  vhost:
    - vhost1
    - vhost2
  www_root: /var/www/my_host
```

Best regards.

**Comment by MasterMind2k** [comment]
Hi.

Would something like this be apropriate?
https://github.com/MasterMind2k/puppet-nginx/commit/0c56a869dc1e92c7c678854d7b1e0825dfdfcf3a

Best regards.

**Comment by kwisatz** [comment]
This looks like a duplicate of #1135 and I'd close this on in favor of the latter because it's more recent and uses the current hiera syntax.
