### ISSUE TITLE
Multiple Locations

### ISSUE THREAD

**Issue by charles-d-burton** [voxpupuli/puppet-nginx#645]
I'm trying to build a config that looks like something like this:

vhost
   -location
   -location
   -location

Currently I have the configs setup this way:

```ruby
class profiles::gsdnginx {
    class { 'nginx':
        template => "nginx/conf.d/nginx.conf.erb",
        worker_connections => 4096,
    }

    file { "/web/":
        ensure => "directory",
        owner => "nginx",
        group => "nginx",
        mode => 750,
        seltype => "httpd_config_t",
    }

    nginx::resource::vhost { "${fqdn}":
        ensure => present,
        www_root => "/web",
        index_files => [ 'index.html' ],
    }
}
```
That's the class that I'm using as a general nginx configuration in a profile that will eventually be attached to a role.  Then I created a module that's going to have the individual configs in it for each reverse proxy location:

```ruby
class pub_web_locations::uats {
   nginx::resource::location { "meteorsrv-dev.wx.noaa.gov":
      ensure    => present,
      vhost     => "${fqdn}",
      location  => '/uats',
      proxy     => "http://meteorsrv-dev.wx.noaa.gov/uats",
   }
}
```
```ruby
class pub_web_locations::vrmc {
   nginx::resource::location { "vrmc-ta1.fsl.noaa.gov":
      ensure    => present,
      vhost     => "${fqdn}",
      location  => '/vrmc',
      proxy     => "http://vrmc-ta1.fsl.noaa.gov:8080/nevs.vrmc/",
   }
}
```

It seemed to work once, but then after making some edits puppet just spits out this error at me:

Error: Failed to apply catalog: Could not find filebucket  specified in backup

Not sure what I'm doing wrong.

**Comment by dhoppe** [comment]
Hello,

it looks like you have stumbled upon an issue regarding concat. I think in the meantime your problem has been resolved and I will close this issue. 

https://tickets.puppetlabs.com/browse/MODULES-2006
