### ISSUE TITLE
Adding iphash to Upstream has no effect

### ISSUE THREAD

**Issue by BnMcG** [voxpupuli/puppet-nginx#661]
My Puppet config looks as so:

```
# NGINX config
        class { 'nginx': }

        $upstream_config = {
                'ip_hash'   => '',
                'keepalive' => '20',
        }

        nginx::resource::upstream { 'app_app':
                members => [
                        '10.99.0.10',
                ],
                upstream_cfg_prepend => $upstream_config,
        }

        nginx::resource::vhost { 'app.app.com':
                proxy => 'http://app_app',
                ipv6_enable => true,
        }
```

When applying my configuration, the "keepalive" value seems to be set in the actual configuration file, but iphash does not:

```
upstream app_app {


  keepalive 20;

  server     10.99.0.10  fail_timeout=10s;
}
```

Have I done something wrong? Why isn't ip_hash being enabled? I installed the module today so I guess I have the latest version.

**Comment by BnMcG** [comment]
After a little playing around, this seems to work if I specify: 

```
'ip_hash'   => ' ',
```

(Note the extra space between the ''s), but specifying an empty value as I saw in the documentation in the module source code does not work.

**Comment by wyardley** [comment]
As mentioned in #563, I tried using '' (via hiera), and it did seem to work. Are you still able to reproduce this issue @BnMcG (with a recent version of the module)?
