### ISSUE TITLE
Parameters for log_format

### ISSUE THREAD

**Issue by goldsap25** [voxpupuli/puppet-nginx#678]
I need to set the log_format values but not sure how to do this. I was not able to find documentation regarding this.

By default, it's setting $log_format: {}
I need it to be set such that it looks like below. (skipping other values within http)

http{
  log_format main 'some string with some var like $remote_addr'
                            'another string'
                            'one more string'
}

If this is the wrong place to post question, please let me know where I may post this question.

Thanks!

**Comment by Griphon** [comment]
Just add
```
class { '::nginx::config':
  ...
  log_format => {
    main      => 'some string with some var like $remote_addr',
    alternate => 'another string',
    combined  => '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"',
  }
  ...
}
```

**Comment by goldsap25** [comment]
When I used the format provided, it created following on the conf file.
> log_format alternate '$status $body_bytes_sent "$http_referer" ';
> log_format combined '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';
> log_format main '$remote_addr - $remote_user [$time_local] "$request" ';

And it fails the config check. log_format should not be repeated, it seems. :( 
I have it working for now by adding a module that pastes in the exact content that I want but wanted to check if it was possible to generate the multiline for log_format without repeating log_format.

> log_format main '$remote_addr - $remote_user [$time_local] "$request" ';
>                            '$status $body_bytes_sent "$http_referer" ';
>                            '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';

**Comment by Griphon** [comment]
@goldsap25, I use 2 formats and it seems to be ok. Try to remove format `combined` as it's predefined

**Comment by wyardley** [comment]
I'm going to close this one; @goldsap25, please reopen or file a new issue if you're still experiencing problems.

**Comment by soudaburger** [comment]
I know this is closed, but I just wanted to add that I solved this with crazy inline escaping in hiera.  Wondering if there's a better way to handle this?

`nginx::log_format
 main: "$remote_addr - $remote_user [$time_local] \"$request\"'\n\t\t  '$status $body_bytes_sent \"$http_referer\" Via:\"$http_via\" '\n\t\t  '\"$http_user_agent\" \"$http_x_forwarded_for\""
`
