### ISSUE TITLE
fastcgi_params should not be creating non-standard files by default

### ISSUE THREAD

**Issue by XANi** [voxpupuli/puppet-nginx#682]
As it is now, to have empty fastcgi_params file (if, for example, I want to completely manage it from manifest) requires explictly creating empty file, ensuring it is **before** every nginx invocation (which is error-prone) and then passing it as parameter.

Passing `/dev/null` as fastcgi_param just causes puppet to break `/dev/null` permissions

Passing `false` (which should just mean "i dont want that parameter in my config") returns validation error

**Comment by jfryman** [comment]
Can you give me an example of what this looks like in your manifest? 

Likewise, any thoughts about how to model this better are most appreciated.

**Comment by XANi** [comment]
I wanted to disable taking params from file and just pass a list of them in manifest (ceph's radosgw had a bug with default params and I had to turn few of them off)

so I've set up fastcgi-params file to /dev/null, then nginx module chmodded that file and, well, a lot of apps are very unhappy if they can't access /dev/null....

IMO it should either:

* just do not add fastcgi_param config option if `false` is passed to it
* do not manage permissions of that file

**Comment by wyardley** [comment]
This is now being tracked in #862; feel free to follow that if you want to see what ends up happening.
