### ISSUE TITLE
Location ordering

### ISSUE THREAD

**Issue by pruchai** [voxpupuli/puppet-nginx#686]
Is there any way to order locations in the way they are defined in my hiera yaml file? I am trying to go from static configs and erb templates being pushed to servers to automatically generated configs with this module and hiera, and my virtual host config is a mess!  How can i maintain the order of locations?

**Comment by cjeanneret** [comment]
I need the same kind of thing. According to the doc, order *is* important especially for regexp:
```
[…]the location with the longest matching prefix is selected and remembered. Then regular
expressions are checked, in the order of their appearance in the configuration file. The search of
regular expressions terminates on the first match, and the corresponding configuration is used
```
[source](http://nginx.org/en/docs/http/ngx_http_core_module.html#location)

**Comment by cjeanneret** [comment]
Ah, didn't see the ```$priority``` parameter for location resource.

Might be cool to order the parameters so that we can find them faster…

**Comment by dhoppe** [comment]
Hello, 

this is a mighty module. I do not think ordering the parameters would change anything. But patches regarding the documentation of this module are always welcome. 

https://github.com/voxpupuli/puppet-nginx/blob/master/manifests/resource/location.pp#L90-L92
