### ISSUE TITLE
Nested Locations

### ISSUE THREAD

**Issue by hopperd** [voxpupuli/puppet-nginx#692]
It would be nice if there was a more native way then using raw_(append|prepend) for configuration of nested locations.

**Comment by jfryman** [comment]
Do you have any proposals?

**Comment by split3** [comment]
I've been trying to think of the cleanest way to do it and haven't come up with anything I like yet.  I'm working right now on support for [stream](http://nginx.org/en/docs/stream/ngx_stream_core_module.html) as that has a higher priority for us.

**Comment by wyardley** [comment]
I'm going to close this for now, if someone wants to submit a PR, or at least some specific examples and a proposed interface, feel free to comment here or open a new PR / issue.
