### ISSUE TITLE
Changing the vhost / location doesn't reload the server

### ISSUE THREAD

**Issue by jlory** [voxpupuli/puppet-nginx#706]
When you change the vhost / location it doesn't reload the server. Not sure why it's not working, when I change nginx.conf it does work but not files in sites-available.

**Comment by dhoppe** [comment]
Hello, 

can you give us an example? According to this [file](https://github.com/voxpupuli/puppet-nginx/blob/master/manifests/resource/vhost.pp#L551-L560) resource the service should be restarted.

**Comment by wyardley** [comment]
This has always worked as expected for me too.
