### ISSUE TITLE
Allow multiple access_log within server{} ( files + syslog )

### ISSUE THREAD

**Issue by jlory** [voxpupuli/puppet-nginx#710]
It seems that we can't have multiple access_log in the vhost conf, the reason why you would need more that one is if you have to log to a file and also send logs to syslog.

Is there a quick fix without modifying the existing code?

**Comment by GosthMan** [comment]
Yes there is add it like this
access_log: syslog:server=logs:12301 graylog2_format; access_log            /var/log/nginx/prod.ext.oca.com.ar.access.log
just change the server=logs with your server

**Comment by wyardley** [comment]
#888 adds this functionality in both main config and vhosts, though you can't set the format differently for each acess_log directive (without using the workaround above).
