### ISSUE TITLE
upstream_cfg_append

### ISSUE THREAD

**Issue by frankvolkel** [voxpupuli/puppet-nginx#717]
There's no option to append config for upstream, this is currently not possible: 

```
upstream backend {
    server backend1.example.com;
    server backend2.example.com;

    sticky cookie srv_id expires=1h domain=.example.com path=/;
}
```

It'd be great if upstream_cfg_append is available

**Comment by wyardley** [comment]
There is an `$upstream_cfg_prepend` option.... adding append should be pretty easy. I'm guessing the order is mostly a cosmetic thing?

Is anyone willing to submit a PR for this? Should be mostly copy / pasta.

**Comment by wyardley** [comment]
Ok, not sure if you still need this, but it's reasonable and didn't take too long to add.
#953

**Comment by wyardley** [comment]
@frankvolkel If this is still something you use / want, please test if possible. Assuming this gets merged, should make the next module release, but you can get a patch from the PR above if you want to test.

**Comment by wyardley** [comment]
This is now merged, going to close this ticket for now.
