### ISSUE TITLE
white space

### ISSUE THREAD

**Issue by gerases** [voxpupuli/puppet-nginx#742]
Hi,

I see a lot of untrimmed whitespace in the resulting nginx vhosts. For example:

    ssl_prefer_server_ciphers on;

    index  index.html index.htm index.php;

Was wondering if you were aware of it and whether a fix is coming.

Thanks!!

**Comment by jfryman** [comment]
@gerases Pull requests are always accepted! TIA! :bow:

**Comment by gerases** [comment]
​Hi James,

I can do a pull request, but I'm not sure if what I've fixed is a
comprehensive​e fix. I can submit what I have and you extrapolate from
there?

Thanks,
   Sergei

**Comment by 3flex** [comment]
@gerases even if it's not comprehensive, it will still be an improvement, so don't be scared to submit something that doesn't necessarily cover all cases!

**Comment by 3flex** [comment]
Closing this as it's not an issue that affects the functionality of the module. PRs to improve the situation would be welcome!

**Comment by igalic** [comment]
@3flex imo, it affects the usability of the module, and that, definitely is an issue that needs to be addressed.

**Comment by wyardley** [comment]
I put in a PR that's a first pass at cleaning up the spacing a little: https://github.com/voxpupuli/puppet-nginx/pull/891

**Comment by igalic** [comment]
with #891 i'm going to close this issue for now
