### ISSUE TITLE
include /etc/nginx/streams-available|enabled not in nginx.conf.erb

### ISSUE THREAD

**Issue by alwiesner** [voxpupuli/puppet-nginx#780]
When attempting to build a configuration for a stream host, I am able to successfully build a  stream{} section in the main nginx.conf file, which correctly includes:  /etc/nginx/conf.stream.d/*.

When actually building the streamhost, it correctly gets placed in the /etc/nginx/streams-available directory/.  However, the stream{} section within nginx.conf, and how it is configured in the .erb template, does not include this directory (include etc/nginx/streams-available/*) when setting up the streamhost.

Can we add support for this?  Is there another way to do this that I am missing?

**Comment by astrostl** [comment]
Looks like a working fix has been awaiting a merge for months over at https://github.com/jfryman/puppet-nginx/pull/784

**Comment by wyardley** [comment]
I've just commented in #784. There is one open PR (#879) by someone else that was already merged that does a partial fix, and I did some other stuff related to this that may yet be merged (#878), but it does seem like support for this is pretty broken as-is.

**Comment by wyardley** [comment]
See #933

**Comment by wyardley** [comment]
This should be now be resolved in #933, which is in the most recent release (0.5.0)
