### ISSUE TITLE
'server {' stanza

### ISSUE THREAD

**Issue by gerases** [voxpupuli/puppet-nginx#792]
Hi,

It seems that the `server {` block is only included under this condition:

```
if (($listen_port + 0) != ($ssl_port + 0)) {
...
```

If therefore I don't want ssl at all, then doing this:

```
  nginx::resource::vhost { 'blah':
    listen_port   => 80,
    proxy         => 'http://localhost:8080',
  }
```

produces just:

```
location / {
...
}
```

But in that case nginx doesn't start with the error:

```
nginx: [emerg] "location" directive is not allowed here
```

Am I doing something wrong?

Thanks

**Comment by gerases** [comment]
Hmm, I can't quite reproduce that behavior anymore. Let's ignore this for now.

**Comment by 0x9090** [comment]
Also running into this issue. My config is,

```
class { 'nginx':
    manage_repo     => false,
    package_ensure  => 'latest',
  }
  nginx::resource::vhost { '###':
    listen_port => 443,
    proxy       => 'http://127.0.0.1:8080',
  }
```
The service running on 127.0.0.1:8080 is terminating TLS

**Comment by gerases** [comment]
What do you get with that configuration?

**Comment by gerases** [comment]
Don't include `listen_port` and it should work

**Comment by wyardley** [comment]
@gerases: If it's Ok, I'm going to close this one out.
