### ISSUE TITLE
Is this module still "undergoing some structural maintenance"?

### ISSUE THREAD

**Issue by mc0e** [voxpupuli/puppet-nginx#809]
It looks like that notice (i.e. at the top of the README.md) has been there quite some time, and I'm thinking things might have settled by now?

It might still be useful to put something in about transition from puppet versions  before 3.x, but the wording of the notice wants to be revisited I think.

Just a few lines further down, the Requirements section refers to puppet 2.7.  Maybe the notice should be moved to there with a note like  "but see https://github.com/jfryman/puppet-nginx/blob/master/docs/hiera.md for puppet versions before 3.x".  Maybe also reference hiera in that list?  Distinguish between recommended vs required?

**Comment by 3flex** [comment]
@jfryman can hopefully weigh in here...

**Comment by 3flex** [comment]
Short answer, yes, the structural maintenance is still somewhat a WIP. However we need additional resources to help - this module's looking for a new maintainer, see #844.

For the specific feedback you had, please consider submitting a PR for review. Thanks!
