### ISSUE TITLE
HTTP->HTTPS

### ISSUE THREAD

**Issue by dowlingw** [voxpupuli/puppet-nginx#818]
Feature request: Add a `https_redirect` option to the `vhost` type that will:

- Implies `ssl_only` for the default location
- Installs an additional location with `ssl => false` that performs a temporary or permanent HTTP redirect to the same URL at HTTPS.

This will significantly reduce the amount of boilerplate resources required to do HTTPS-only sites with a friendly redirection for HTTP visitors.

I should be able to generate a PR, but will need some assistance with rspec because n00b.

**Comment by pckls** [comment]
Happy to assist with the testing :)

**Comment by wyardley** [comment]
I think $rewrite_to_https does this, though it would be easier to find if it had 'ssl' in the parameter name and / or was grouped with the SSL related parameters. Can you see if that works for you?

**Comment by wyardley** [comment]
Feature already exists, though do want to support setting the redirect port, and possibly rename the config option to be more obvious.
