### ISSUE TITLE
Tag request

### ISSUE THREAD

**Issue by Slm0n87** [voxpupuli/puppet-nginx#843]
The last tag v0.3.0 is from 6th February 2016.  
Is there a plan to create tags periodically?

**Comment by 3flex** [comment]
We're working on one, but see #844 for more.

**Comment by 3flex** [comment]
@Slm0n87 I'm going to close this since the module has been moved to voxpupuli's management and a new version will be tagged and released to the Forge in the next day or two.

Going forward you can expect more frequent releases.
