### ISSUE TITLE
Add File Output Preview

### ISSUE THREAD

**Issue by moserja** [voxpupuli/puppet-nginx#846]
It would be nice if you could have 2 columns for your examples. 1. that shows the puppet code 2. What file gets created on the system and the contents of that file

Example:

nginx::nginx_vhosts:
  'testsite.org':
      ssl: true

Creates file: sites-enabled/testsite.org 
server {
  listen       *:443 ssl;
  server_name  testsite.org;

  ssl on;
}

**Comment by wyardley** [comment]
Thanks for the feedback. I do hope we can make some improvements to the docs in general, and we will take this suggestion under consideration.
