### ISSUE TITLE
Improvement of the hiera-related documentation

### ISSUE THREAD

**Issue by ubellavance** [voxpupuli/puppet-nginx#892]
Hi,

I just started using this module and I appreciate the fact that you're pushing towards hiera, which is a wonderfull way to manage configs. However, I feel that the hiera-related documentation for this module is a bit short.  I could contribute some text and sample code if someone else would be willing to contribute as well (at least to validate my work).

**Comment by wyardley** [comment]
Agreed! I was just thinking the same thing... 
The "Hiera Support" section in README.md is decent, but there are no references back to it (or further examples) in docs/hiera.md (ironically) or in examples/.

I'm happy to look over / merge docs related pull-requests to improve the hiera docs.

**Comment by wyardley** [comment]
Short answer, pull requests gratefully accepted.

Feel free to ping me or the Voxpupuli folks in the places I mentioned in another ticket. I'm going to close this one for now.

**Comment by ubellavance** [comment]
Understood. I need to do more testing and understand some information about the module and then I could submit Hiera-related documentation for this module.
