### ISSUE TITLE
Defaults

### ISSUE THREAD

**Issue by ubellavance** [voxpupuli/puppet-nginx#896]
Hi,

is there a reason why the module doesn't use the binary's default values?  I think that a module should never set defaults other than the binary's unless it is necessary.  By necessary, I mean that nginx doesn't start at all if this or these parameters are not set correctly.

As an example, the module sets accept_mutex to on, while it is disabled by default in [nginx](http://nginx.org/en/docs/ngx_core_module.html#accept_mutex) and in the package's nginx.conf file.

There are many parameters like that...  I have checked on RHEL and Ubungu 16.04 and I don't see that many parameters in the conf file.

Thanks,

**Comment by wyardley** [comment]
The particular example seems to have come from #747. That claimed that it used defaults, so either the nginx default has changed, or that was a mistake. @mlrobinson: any idea about that? I've created #903 to address that specific example.

As far as the more general problem, it is an issue when defaults get in the module vs. just leaving them out of the file, but in some cases it's necessary. From what I've seen, folks have tried to use default settings when they add parameters; this module has a lot of contributions from a lot of different people, so things do occasionally fall through the cracks. If you want to come up with a full list of params that don't match the defaults, we can try to get things synced up. Or, if you'd like to take a crack at correcting them in a pull-request, adjusting any tests as needed, we can take a look at that.

**Comment by ubellavance** [comment]
Thanks for the PR for that, but I don't think that is the solution.  As you can see [here](http://nginx.org/en/docs/ngx_core_module.html#accept_mutex), "Prior to version 1.11.3, the default value was on." It means that nginx 1.10 default was on.  Most systems have nginx < 1.11.3, so almost all installs has "on" as default, so putting it to yes would break most installs. The more, more general problem is that, in my opinion, a module shouldn't re-state the defaults of the moment, it should just not set any parameter unless necessary.  As an example, you can look at [this module](https://github.com/edestecd/puppet-clamav/blob/master/manifests/params.pp). Clamd has a million parameters, but the module only defines the ones that are necessary and let the users define anything that he doesn't want to be at default value.

Defining defaults can be usefull to have a more consistent setup amongst a bunch of different kind of installs (different OSs, different nginx versions), but I think that it should be the responsibility of the puppet admin to check what are the defaults in the version that is to be installed and configure the module parameters accordingly.

It is also less of a management burden for the module maintainers because they don't need to track default values changes, and nginx seems not to be very static on the default values.

**Comment by wyardley** [comment]
Got it, so the default is correct for most versions of nginx that people are using this module with.

I agree with you in principle, that leaving more / most default settings implicit rather than explicit could be a good thing. The behavior could be unpredictable in both good and bad ways, but keeping track of the defaults, and dealing with the situation where the module is managing different nginx versions makes it close to impossible to do something that will behave correctly in all cases. I'm not personally prepared to take on the task of reworking the module to take that approach in more places, but I will leave this issue open so that there can be some more discussion.

**Comment by wyardley** [comment]
There's no "needs discussion" label, but maybe we should have one?
One approach would be to have the parameters exist, but set them to undef instead of to their default value? Then the template could only render them if they are set... not sure if this would cause problems with parameter validation.

**Comment by ubellavance** [comment]
Yes, the parameter should be set to undef, so that if someone needs something else than the defaut, it is easy to do.  I just checked the code again and there are many of them.  It would be easy to just put them to undef, but then comes the validation.  I'm not too familiar with puppet validations but it looks like each related validation will have to be edited to allow an undef value as well.

Most important of all, a warning of some kind (in the README.md) must be shown so the user is aware that from some version, on, no default values are defined unless absolutely necessary.  I think that in the case of nginx, the binary's defaults should be ok, in opposition to clamd which needed at least a tcp port or UNIX socket and a few other things.

Having a "needs discussion" could be good. Do you know anyone that would be interested into discussing on that topic?

**Comment by 3flex** [comment]
@wyardley your two most recent comments exactly reflect my thinking. `undef` as the module's default, which means using nginx's defaults. As you said, it's a lot of work, but can probably be tackled incrementally in many cases, with the remaining ones possibly having to wait until a major version if they're going to cause breakage/changes in behaviour.
