### ISSUE TITLE
nginx::resource::upstream with no members can only be called once

### ISSUE THREAD

**Issue by ikryten** [voxpupuli/puppet-nginx#897]
We define upstreams with no members because we use a custom in-house module to resolve the destination. This use to work fine with an older version of the module. But the latest version assumes that if nginx::resource::upstream has no members defined then you want to collect them. That's all well and good but the collection logic is flawed, the collection is done through a class (class { '::nginx::resource::upstream::collect': ) and classes can only be called once. This effectively means you can only have one upstream defined that uses 'collected' members. This should be addressed. It should be a defined type or just done directly in nginx::resource::upstream.

**Comment by wyardley** [comment]
Related to #832 maybe (which, in turn, was trying to solve #720)?
This is not an area I know well, so don't really want to try and propose a fix...

@ikryten: can't promise that I'll be able to help, but if you could include an example of a config that fails (or, even better, spec tests for how the feature should work), it might be easier for someone to take a look at this.

**Comment by wyardley** [comment]
The newest fix of #755 should revert it to the previous behavior, if it gets rebased and merged.

**Comment by wyardley** [comment]
Merged #755.
