### ISSUE TITLE
Support for Ubuntu 16.04?

### ISSUE THREAD

**Issue by lkthomas** [voxpupuli/puppet-nginx#935]
Is this module support Ubuntu 16.04?

**Comment by bastelfreak** [comment]
Hi @lkthomas, we recently migrated this module in our namespace. Currently we try to work our-self through the open issues and PRs. Right now we havn't tested Ubuntu 16.04, but we are looking for volunteers to help out. Are you able to test the module on Ubuntu16.04 or write spec/acceptance tests for it?

**Comment by wyardley** [comment]
16.04 is now in the available options after the recent modulesync bump. I'll try to run the current acceptance tests about it.
@lkthomas: It should work, and so you're welcome to try it and let us know if you run into any problems. I'll try to add it to metadata.json when we've validated that it works.

**Comment by jarro2783** [comment]
I have used it on Ubuntu 16.04 without any issues.

**Comment by wyardley** [comment]
@jarro2783 Do you have an example? Are you using install_puppet_on?

I opened a ticket @
https://tickets.puppetlabs.com/browse/BKR-970

**Comment by wyardley** [comment]
#951 addresses a few small points (adds it in metadata.json as supported, and adds it to the array of codenames that are looked for in `params`; this means that repos will now be managed where they weren't before. This also resolves an acceptance test problem with 16.04.

#954 should address some bootstrapping issues with acceptance tests for this platform. So, it should sort of work already, but the next release should improve support.

**Comment by jarro2783** [comment]
The issues behind #951 or #954 didn't make a difference for us, because we use bundler to package the puppet version with dependencies that we need, and r10k to install all the external puppet modules. The puppet code seems to work as far as our setup goes, since we just ran it on Ubuntu 16.04 and didn't have any issues.

So I can't comment on any of the meta packaging type stuff, but the module itself seems fine.

**Comment by wyardley** [comment]
@jarro2783: the difference mostly is that `manage_repos` wouldn't have been enabled unless explicitly set, so a pretty small thing, but would have caused slightly different behavior from the current expectations. The other ticket just fixed problems with acceptance tests, so yes, doesn't affect end-users. I'm going to close out this ticket as soon as those PRs get merged.

**Comment by wyardley** [comment]
I'm going to close this for now. Let me know if any other issues come up with 16.
