### ISSUE TITLE
Upstreams do not depend on package

### ISSUE THREAD

**Issue by jarro2783** [voxpupuli/puppet-nginx#942]
The nginx package resource should come before the upstreams. I see the following error in my logs:

```
Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /etc/nginx/conf.d/restapi_pool-upstream.conf20161025-2146-tn3v2u.lock
```

It looks like the config files are trying to be written before the nginx package has installed `/etc/nginx/conf.d`. I can fix it in my own code by writing:

```
Class['nginx::package'] -> Nginx::Resource::Upstream <||>
```

**Comment by joshuaspence** [comment]
This seems to apply to other resources too, such as `Nginx::Resource::Map`.

**Comment by wyardley** [comment]
@jarro2783 @joshuaspence: can you try the most recent release?
I think between #906 and #933 (and possibly one other?) this may now be fixed. If you're still seeing this with 0.5.0, comment here, and I'll reopen.

**Comment by joshuaspence** [comment]
Nope, this is still an issue with 0.5.0. It looks like the problem was fixed for `Nginx::Resource::Vhost`, but not for `Nginx::Resource::Upstream`.

**Comment by wyardley** [comment]
@jarro2783 @joshuaspence: If you're willing / able, can you test out #958 (you can append .diff or .patch to the PR URL to get a patch of it, if that helps).

**Comment by jarro2783** [comment]
As far as I can tell that solves it.

**Comment by wyardley** [comment]
Thanks @jarro2783. PR is now merged, so I'm going to close this issue for now.
