### ISSUE TITLE
Allow access_log to be an array

### ISSUE THREAD

**Issue by ikryten** [voxpupuli/puppet-nginx#975]
access_log can be specified multiple times and I make use of this feature. It would be nice if the puppet module supported this.

**Comment by wyardley** [comment]
@ikryten: in which context? It should support this already in multiple contexts in the current version. See
#888 etc.
In some contexts, you can't set different log types for each file, though hoping to add this and standardize the logging a bit more (#773)

**Comment by ikryten** [comment]
Oh drat, my version is out of date. Sorry, I fired this off without doing my due diligence.

**Comment by wyardley** [comment]
@ikryten No worries. Note that there have been lots of backwards-incompatible changes, so let me know if you run into any problems.
