### ISSUE TITLE
How to implement `return 301` and `listen *:80 default` directives

### ISSUE THREAD

**Issue by rdev5** [voxpupuli/puppet-nginx#979]
Hi,

Just need to know how I can do the following with this module:

Load default site (no vhost found):
````
server {
  listen *:80 default;
  server_name           _;
}
````

Redirect non-SSL with 301:
````
server {
	listen 80;
	server_name example.com;
	return 301 https://$host$request_uri;
}
````

**Comment by wyardley** [comment]
You can use `_` as a literal in the `server_name` parameter (which can take an array or string), so in a simple use case, you can just set the `server_name` parameter to `_`.

With current version, you can just define the vhost once and define the `ssl_redirect` parameter. There are a couple other ssl_ options, see the limited docs that are there now, as well as the parameters documented for the vhost resource: https://github.com/voxpupuli/puppet-nginx/blob/master/manifests/resource/vhost.pp

**Comment by ardrigh** [comment]
I have been trying to create a similar server setting for a Confluence install.
I created this manual configuration which I have been using this module to create:

Puppetfile:
```puppet
mod "puppet/nginx", "0.6.0"
```

Manual configuration:
```nginx
  server {
      listen 80 default_server;
      server_name wiki.ard.lan;

      return         301 https://$server_name/;
  }
```

Yaml for this module:
```yaml
nginx::nginx_servers:
  '_':
    ensure: 'present'
    listen_options: 'default_server'
    listen_port: 80
    ssl: false
    ssl_redirect: true
    use_default_location: false
```

Output from the yaml:
```nginx
$ cat _.conf 
# MANAGED BY PUPPET
server {
  listen *:80 default_server;
  server_name           _;

  return 301 https://$host$request_uri;
  access_log            /var/log/nginx/_.access.log combined;
  error_log             /var/log/nginx/_.error.log;
}
```

Hopefully the yaml example may help anyone else reading this ticket.

Without the `use_default_location: true` option this module has a bug causing nginx to fail to restart.

**Comment by noni73** [comment]
The url for vhost resource is changed in PR[#980](https://github.com/voxpupuli/puppet-nginx/pull/980) to server resource https://github.com/voxpupuli/puppet-nginx/blob/master/manifests/resource/server.pp

**Comment by wyardley** [comment]
I'm going to close this; reopen if any more help is needed.
