### ISSUE TITLE
Please add a 'warn' when someone is using 'nginx::resource::vhost' without previously including the nginx class

### ISSUE THREAD

**Issue by law** [voxpupuli/puppet-nginx#983]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.x
- Ruby: 2.3.x
- Distribution: Ubuntu
- Module version: 0.5.0

## How to reproduce (e.g Puppet code you use)
Given Hiera data like: 
```
role::web::myhost_nginx_vhosts:
  'somehost.mycorp.lan':
    www_root: '/var/www'
    listen_options: 'default_server'
    server_name: ["%{networking.fqdn}"]
    access_log: '/var/log/nginx/myhost-access.log'
    error_log: '/var/log/nginx/myhost-error.log'
```

and instantiating it in a far-flung role with
```
class role::web ($myhost_nginx_vhosts) {
  create_resources('nginx::resource::vhost', $myhost_nginx_vhosts)
} 

```
there will be failures along the lines of: 
`Evaluation Error: Error while evaluating a Function Call, nil is not an Array.  It looks to be a NilClass at /etc/puppetlabs/code/environments/vagrant/modules/nginx/manifests/resource/vhost.pp:407:3 at /etc/puppetlabs/code/environments/vagrant/modules/role/manifests/web.pp:1 on node blasrgh
`
  This provides few hints as to the root cause of the error, which in this case is our hapless hero forgot to put: 
`class { 'nginx': }`

in the role, kicking off three days of hair-pulling debugging, swearing, and kicking things.  Total PEBKAC, yes, but having
`unless defined('class nginx { warn('You might want to consider including the nginx class if you are getting strange evaluation errors') }` 

would've been MOST helpful.  
## What are you seeing
Red.  Mainly from my own foibles.  

## What behaviour did you expect instead
I expected the module to compile without complaint, but I would've settled for a warning informing me the 'nginx' parent class was not included when I tried to use the vhost defined-type.

**Comment by vinzent** [comment]
I think it should not only warn it should fail. the defined type wants to read defaults from the ::ngninx class - which it only can if it is already parsed. the only way to ensure this is to explicitly include it before defining a resource.
