### ISSUE TITLE
Add Oracle as one of Redhat operating systems for params file

### ISSUE THREAD

**Issue by patchsmyle** [voxpupuli/puppet-nginx#988]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:  3.7
- Ruby: 
- Distribution: 
- Module version:  0.5

## What are you seeing
Oracle is caught by the RedHat Family, but not by the module_os_overrides key.

## What behaviour did you expect instead
To toggle the 'manage_repo' key to True

Current code:
===========
    'RedHat': {
      if ($::operatingsystem in ['RedHat', 'CentOS'] and $::operatingsystemmajrelease in ['5', '6', '7']) {
        $_module_os_overrides = {
          'manage_repo' => true,
        }

Suggested edit:
============
    'RedHat': {
      if ($::operatingsystem in ['RedHat', 'CentOS','Oracle'] and $::operatingsystemmajrelease in ['5', '6', '7']) {
        $_module_os_overrides = {
          'manage_repo' => true,
        }

**Comment by wyardley** [comment]
@patchsmyle is the versioning the same as vanilla RedHat? If so, this is indeed a fairly easy fix.
